BEGIN;

DROP INDEX IF EXISTS idx_plans_slug;
ALTER TABLE plans DROP COLUMN IF EXISTS slug;
ALTER TABLE plans DROP COLUMN IF EXISTS price_monthly;
ALTER TABLE plans DROP COLUMN IF EXISTS price_hourly;
ALTER TABLE plans DROP COLUMN IF EXISTS updated_at;

COMMIT;
