BEGIN;
ALTER TABLE plans ADD COLUMN IF NOT EXISTS max_snapshots INTEGER NOT NULL DEFAULT 5;
ALTER TABLE plans ADD COLUMN IF NOT EXISTS max_backups INTEGER NOT NULL DEFAULT 10;
ALTER TABLE plans ADD COLUMN IF NOT EXISTS max_iso_count INTEGER NOT NULL DEFAULT 3;
COMMIT;
