// VirtueStack NodeAgentService - gRPC API Definition
//
// This service provides the primary interface for managing virtual machines
// on individual compute nodes within the VirtueStack infrastructure.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: virtuestack/node_agent.proto

package nodeagent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeAgentService_CreateVM_FullMethodName                  = "/virtuestack.nodeagent.NodeAgentService/CreateVM"
	NodeAgentService_StartVM_FullMethodName                   = "/virtuestack.nodeagent.NodeAgentService/StartVM"
	NodeAgentService_StopVM_FullMethodName                    = "/virtuestack.nodeagent.NodeAgentService/StopVM"
	NodeAgentService_ForceStopVM_FullMethodName               = "/virtuestack.nodeagent.NodeAgentService/ForceStopVM"
	NodeAgentService_DeleteVM_FullMethodName                  = "/virtuestack.nodeagent.NodeAgentService/DeleteVM"
	NodeAgentService_ReinstallVM_FullMethodName               = "/virtuestack.nodeagent.NodeAgentService/ReinstallVM"
	NodeAgentService_ResizeVM_FullMethodName                  = "/virtuestack.nodeagent.NodeAgentService/ResizeVM"
	NodeAgentService_MigrateVM_FullMethodName                 = "/virtuestack.nodeagent.NodeAgentService/MigrateVM"
	NodeAgentService_AbortMigration_FullMethodName            = "/virtuestack.nodeagent.NodeAgentService/AbortMigration"
	NodeAgentService_PostMigrateSetup_FullMethodName          = "/virtuestack.nodeagent.NodeAgentService/PostMigrateSetup"
	NodeAgentService_CreateDiskSnapshot_FullMethodName        = "/virtuestack.nodeagent.NodeAgentService/CreateDiskSnapshot"
	NodeAgentService_DeleteDiskSnapshot_FullMethodName        = "/virtuestack.nodeagent.NodeAgentService/DeleteDiskSnapshot"
	NodeAgentService_TransferDisk_FullMethodName              = "/virtuestack.nodeagent.NodeAgentService/TransferDisk"
	NodeAgentService_ReceiveDisk_FullMethodName               = "/virtuestack.nodeagent.NodeAgentService/ReceiveDisk"
	NodeAgentService_PrepareMigratedVM_FullMethodName         = "/virtuestack.nodeagent.NodeAgentService/PrepareMigratedVM"
	NodeAgentService_CreateLVMBackup_FullMethodName           = "/virtuestack.nodeagent.NodeAgentService/CreateLVMBackup"
	NodeAgentService_RestoreLVMBackup_FullMethodName          = "/virtuestack.nodeagent.NodeAgentService/RestoreLVMBackup"
	NodeAgentService_StreamVNCConsole_FullMethodName          = "/virtuestack.nodeagent.NodeAgentService/StreamVNCConsole"
	NodeAgentService_StreamSerialConsole_FullMethodName       = "/virtuestack.nodeagent.NodeAgentService/StreamSerialConsole"
	NodeAgentService_GetVMStatus_FullMethodName               = "/virtuestack.nodeagent.NodeAgentService/GetVMStatus"
	NodeAgentService_GetVMMetrics_FullMethodName              = "/virtuestack.nodeagent.NodeAgentService/GetVMMetrics"
	NodeAgentService_GetNodeResources_FullMethodName          = "/virtuestack.nodeagent.NodeAgentService/GetNodeResources"
	NodeAgentService_CreateSnapshot_FullMethodName            = "/virtuestack.nodeagent.NodeAgentService/CreateSnapshot"
	NodeAgentService_DeleteSnapshot_FullMethodName            = "/virtuestack.nodeagent.NodeAgentService/DeleteSnapshot"
	NodeAgentService_RevertSnapshot_FullMethodName            = "/virtuestack.nodeagent.NodeAgentService/RevertSnapshot"
	NodeAgentService_ListSnapshots_FullMethodName             = "/virtuestack.nodeagent.NodeAgentService/ListSnapshots"
	NodeAgentService_GuestExecCommand_FullMethodName          = "/virtuestack.nodeagent.NodeAgentService/GuestExecCommand"
	NodeAgentService_GuestSetPassword_FullMethodName          = "/virtuestack.nodeagent.NodeAgentService/GuestSetPassword"
	NodeAgentService_GuestFreezeFilesystems_FullMethodName    = "/virtuestack.nodeagent.NodeAgentService/GuestFreezeFilesystems"
	NodeAgentService_GuestThawFilesystems_FullMethodName      = "/virtuestack.nodeagent.NodeAgentService/GuestThawFilesystems"
	NodeAgentService_GuestGetNetworkInterfaces_FullMethodName = "/virtuestack.nodeagent.NodeAgentService/GuestGetNetworkInterfaces"
	NodeAgentService_GetBandwidthUsage_FullMethodName         = "/virtuestack.nodeagent.NodeAgentService/GetBandwidthUsage"
	NodeAgentService_SetBandwidthLimit_FullMethodName         = "/virtuestack.nodeagent.NodeAgentService/SetBandwidthLimit"
	NodeAgentService_ResetBandwidthCounters_FullMethodName    = "/virtuestack.nodeagent.NodeAgentService/ResetBandwidthCounters"
	NodeAgentService_Ping_FullMethodName                      = "/virtuestack.nodeagent.NodeAgentService/Ping"
	NodeAgentService_GetNodeHealth_FullMethodName             = "/virtuestack.nodeagent.NodeAgentService/GetNodeHealth"
)

// NodeAgentServiceClient is the client API for NodeAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NodeAgentService provides VM lifecycle management and monitoring capabilities
// for a single compute node in the VirtueStack cluster.
type NodeAgentServiceClient interface {
	// CreateVM provisions a new virtual machine with the specified configuration.
	// This includes disk provisioning from a template and network configuration.
	CreateVM(ctx context.Context, in *CreateVMRequest, opts ...grpc.CallOption) (*CreateVMResponse, error)
	// StartVM powers on a stopped virtual machine.
	// The VM must be in STOPPED or CRASHED state to be started.
	StartVM(ctx context.Context, in *VMIdentifier, opts ...grpc.CallOption) (*VMOperationResponse, error)
	// StopVM gracefully shuts down a running virtual machine using ACPI.
	// The operation will wait for the specified timeout before returning.
	StopVM(ctx context.Context, in *StopVMRequest, opts ...grpc.CallOption) (*VMOperationResponse, error)
	// ForceStopVM immediately terminates a virtual machine (power off).
	// Use with caution as this may cause data loss.
	ForceStopVM(ctx context.Context, in *VMIdentifier, opts ...grpc.CallOption) (*VMOperationResponse, error)
	// DeleteVM permanently removes a virtual machine and its disk image.
	// The VM must be stopped before deletion.
	DeleteVM(ctx context.Context, in *DeleteVMRequest, opts ...grpc.CallOption) (*VMOperationResponse, error)
	// ReinstallVM reimages a virtual machine from a new template.
	// All existing data on the VM will be lost.
	ReinstallVM(ctx context.Context, in *ReinstallVMRequest, opts ...grpc.CallOption) (*CreateVMResponse, error)
	// ResizeVM modifies the resource allocation for a virtual machine.
	// Some changes may require a VM restart to take effect.
	ResizeVM(ctx context.Context, in *ResizeVMRequest, opts ...grpc.CallOption) (*VMOperationResponse, error)
	// MigrateVM transfers a running VM to another compute node.
	// Supports both live migration and offline migration.
	MigrateVM(ctx context.Context, in *MigrateVMRequest, opts ...grpc.CallOption) (*MigrateVMResponse, error)
	// AbortMigration cancels an in-progress VM migration.
	// The VM will remain on the source node.
	AbortMigration(ctx context.Context, in *VMIdentifier, opts ...grpc.CallOption) (*VMOperationResponse, error)
	// Post-migration hook for bandwidth re-application
	PostMigrateSetup(ctx context.Context, in *PostMigrateSetupRequest, opts ...grpc.CallOption) (*VMOperationResponse, error)
	// Create a point-in-time snapshot of a VM disk for migration.
	CreateDiskSnapshot(ctx context.Context, in *CreateDiskSnapshotRequest, opts ...grpc.CallOption) (*CreateDiskSnapshotResponse, error)
	// Remove a disk snapshot created during migration.
	DeleteDiskSnapshot(ctx context.Context, in *DeleteDiskSnapshotRequest, opts ...grpc.CallOption) (*VMOperationResponse, error)
	// Transfer a disk from this node to a target node (streaming).
	TransferDisk(ctx context.Context, in *TransferDiskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DiskChunk], error)
	// Receive a disk transfer from a source node (streaming).
	ReceiveDisk(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DiskChunk, ReceiveDiskResponse], error)
	// Prepare a VM on this node using a transferred disk.
	PrepareMigratedVM(ctx context.Context, in *PrepareMigratedVMRequest, opts ...grpc.CallOption) (*VMOperationResponse, error)
	// CreateLVMBackup creates a sparse backup file from an LVM thin snapshot.
	// Used for LVM VM backup operations.
	CreateLVMBackup(ctx context.Context, in *CreateLVMBackupRequest, opts ...grpc.CallOption) (*CreateLVMBackupResponse, error)
	// RestoreLVMBackup restores an LVM thin LV from a backup file.
	// The thin LV must already exist; this overwrites it in-place.
	RestoreLVMBackup(ctx context.Context, in *RestoreLVMBackupRequest, opts ...grpc.CallOption) (*VMOperationResponse, error)
	// StreamVNCConsole establishes a bidirectional VNC console stream.
	// Used for graphical console access to the VM.
	StreamVNCConsole(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[VNCFrame, VNCFrame], error)
	// StreamSerialConsole establishes a bidirectional serial console stream.
	// Used for text-based console access to the VM.
	StreamSerialConsole(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SerialData, SerialData], error)
	// GetVMStatus retrieves the current operational state of a virtual machine.
	GetVMStatus(ctx context.Context, in *VMIdentifier, opts ...grpc.CallOption) (*VMStatusResponse, error)
	// GetVMMetrics retrieves real-time resource utilization metrics for a VM.
	GetVMMetrics(ctx context.Context, in *VMIdentifier, opts ...grpc.CallOption) (*VMMetricsResponse, error)
	// GetNodeResources retrieves aggregate resource information for the node.
	GetNodeResources(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeResourcesResponse, error)
	// CreateSnapshot creates a point-in-time snapshot of a VM's disk.
	// The VM can be running or stopped during snapshot creation.
	CreateSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*Snapshot, error)
	// DeleteSnapshot removes a previously created disk snapshot.
	DeleteSnapshot(ctx context.Context, in *SnapshotIdentifier, opts ...grpc.CallOption) (*VMOperationResponse, error)
	// RevertSnapshot restores a VM to a previous snapshot state.
	// The VM must be stopped before reverting.
	RevertSnapshot(ctx context.Context, in *SnapshotIdentifier, opts ...grpc.CallOption) (*VMOperationResponse, error)
	// ListSnapshots retrieves all snapshots for a given virtual machine.
	ListSnapshots(ctx context.Context, in *VMIdentifier, opts ...grpc.CallOption) (*SnapshotListResponse, error)
	// GuestExecCommand executes a command inside the VM via the QEMU guest agent.
	// Requires the guest agent to be installed and running in the VM.
	GuestExecCommand(ctx context.Context, in *GuestExecRequest, opts ...grpc.CallOption) (*GuestExecResponse, error)
	// GuestSetPassword changes a user password inside the VM.
	// Requires the QEMU guest agent to be installed and running.
	GuestSetPassword(ctx context.Context, in *GuestPasswordRequest, opts ...grpc.CallOption) (*VMOperationResponse, error)
	// GuestFreezeFilesystems freezes all filesystems in the VM.
	// Used for consistent backup operations.
	GuestFreezeFilesystems(ctx context.Context, in *VMIdentifier, opts ...grpc.CallOption) (*VMOperationResponse, error)
	// GuestThawFilesystems unfreezes all filesystems in the VM.
	// Used after backup operations are complete.
	GuestThawFilesystems(ctx context.Context, in *VMIdentifier, opts ...grpc.CallOption) (*VMOperationResponse, error)
	// GuestGetNetworkInterfaces retrieves network interface information from the VM.
	// Requires the QEMU guest agent to be installed and running.
	GuestGetNetworkInterfaces(ctx context.Context, in *VMIdentifier, opts ...grpc.CallOption) (*GuestNetworkResponse, error)
	// GetBandwidthUsage retrieves current network bandwidth usage for a VM.
	GetBandwidthUsage(ctx context.Context, in *VMIdentifier, opts ...grpc.CallOption) (*BandwidthUsageResponse, error)
	// SetBandwidthLimit applies a bandwidth cap to a VM's network interface.
	SetBandwidthLimit(ctx context.Context, in *BandwidthLimitRequest, opts ...grpc.CallOption) (*VMOperationResponse, error)
	// ResetBandwidthCounters resets the bandwidth usage counters for a VM.
	ResetBandwidthCounters(ctx context.Context, in *VMIdentifier, opts ...grpc.CallOption) (*VMOperationResponse, error)
	// Ping verifies the node agent service is responsive.
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PingResponse, error)
	// GetNodeHealth retrieves comprehensive health status of the node.
	GetNodeHealth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeHealthResponse, error)
}

type nodeAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeAgentServiceClient(cc grpc.ClientConnInterface) NodeAgentServiceClient {
	return &nodeAgentServiceClient{cc}
}

func (c *nodeAgentServiceClient) CreateVM(ctx context.Context, in *CreateVMRequest, opts ...grpc.CallOption) (*CreateVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVMResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_CreateVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) StartVM(ctx context.Context, in *VMIdentifier, opts ...grpc.CallOption) (*VMOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMOperationResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_StartVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) StopVM(ctx context.Context, in *StopVMRequest, opts ...grpc.CallOption) (*VMOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMOperationResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_StopVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) ForceStopVM(ctx context.Context, in *VMIdentifier, opts ...grpc.CallOption) (*VMOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMOperationResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_ForceStopVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) DeleteVM(ctx context.Context, in *DeleteVMRequest, opts ...grpc.CallOption) (*VMOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMOperationResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_DeleteVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) ReinstallVM(ctx context.Context, in *ReinstallVMRequest, opts ...grpc.CallOption) (*CreateVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVMResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_ReinstallVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) ResizeVM(ctx context.Context, in *ResizeVMRequest, opts ...grpc.CallOption) (*VMOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMOperationResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_ResizeVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) MigrateVM(ctx context.Context, in *MigrateVMRequest, opts ...grpc.CallOption) (*MigrateVMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrateVMResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_MigrateVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) AbortMigration(ctx context.Context, in *VMIdentifier, opts ...grpc.CallOption) (*VMOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMOperationResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_AbortMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) PostMigrateSetup(ctx context.Context, in *PostMigrateSetupRequest, opts ...grpc.CallOption) (*VMOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMOperationResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_PostMigrateSetup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) CreateDiskSnapshot(ctx context.Context, in *CreateDiskSnapshotRequest, opts ...grpc.CallOption) (*CreateDiskSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDiskSnapshotResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_CreateDiskSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) DeleteDiskSnapshot(ctx context.Context, in *DeleteDiskSnapshotRequest, opts ...grpc.CallOption) (*VMOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMOperationResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_DeleteDiskSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) TransferDisk(ctx context.Context, in *TransferDiskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DiskChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeAgentService_ServiceDesc.Streams[0], NodeAgentService_TransferDisk_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TransferDiskRequest, DiskChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgentService_TransferDiskClient = grpc.ServerStreamingClient[DiskChunk]

func (c *nodeAgentServiceClient) ReceiveDisk(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[DiskChunk, ReceiveDiskResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeAgentService_ServiceDesc.Streams[1], NodeAgentService_ReceiveDisk_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DiskChunk, ReceiveDiskResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgentService_ReceiveDiskClient = grpc.ClientStreamingClient[DiskChunk, ReceiveDiskResponse]

func (c *nodeAgentServiceClient) PrepareMigratedVM(ctx context.Context, in *PrepareMigratedVMRequest, opts ...grpc.CallOption) (*VMOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMOperationResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_PrepareMigratedVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) CreateLVMBackup(ctx context.Context, in *CreateLVMBackupRequest, opts ...grpc.CallOption) (*CreateLVMBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLVMBackupResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_CreateLVMBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) RestoreLVMBackup(ctx context.Context, in *RestoreLVMBackupRequest, opts ...grpc.CallOption) (*VMOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMOperationResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_RestoreLVMBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) StreamVNCConsole(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[VNCFrame, VNCFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeAgentService_ServiceDesc.Streams[2], NodeAgentService_StreamVNCConsole_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[VNCFrame, VNCFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgentService_StreamVNCConsoleClient = grpc.BidiStreamingClient[VNCFrame, VNCFrame]

func (c *nodeAgentServiceClient) StreamSerialConsole(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SerialData, SerialData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeAgentService_ServiceDesc.Streams[3], NodeAgentService_StreamSerialConsole_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SerialData, SerialData]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgentService_StreamSerialConsoleClient = grpc.BidiStreamingClient[SerialData, SerialData]

func (c *nodeAgentServiceClient) GetVMStatus(ctx context.Context, in *VMIdentifier, opts ...grpc.CallOption) (*VMStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMStatusResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_GetVMStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) GetVMMetrics(ctx context.Context, in *VMIdentifier, opts ...grpc.CallOption) (*VMMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMMetricsResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_GetVMMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) GetNodeResources(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeResourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeResourcesResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_GetNodeResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) CreateSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*Snapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Snapshot)
	err := c.cc.Invoke(ctx, NodeAgentService_CreateSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) DeleteSnapshot(ctx context.Context, in *SnapshotIdentifier, opts ...grpc.CallOption) (*VMOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMOperationResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_DeleteSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) RevertSnapshot(ctx context.Context, in *SnapshotIdentifier, opts ...grpc.CallOption) (*VMOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMOperationResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_RevertSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) ListSnapshots(ctx context.Context, in *VMIdentifier, opts ...grpc.CallOption) (*SnapshotListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotListResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_ListSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) GuestExecCommand(ctx context.Context, in *GuestExecRequest, opts ...grpc.CallOption) (*GuestExecResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GuestExecResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_GuestExecCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) GuestSetPassword(ctx context.Context, in *GuestPasswordRequest, opts ...grpc.CallOption) (*VMOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMOperationResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_GuestSetPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) GuestFreezeFilesystems(ctx context.Context, in *VMIdentifier, opts ...grpc.CallOption) (*VMOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMOperationResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_GuestFreezeFilesystems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) GuestThawFilesystems(ctx context.Context, in *VMIdentifier, opts ...grpc.CallOption) (*VMOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMOperationResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_GuestThawFilesystems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) GuestGetNetworkInterfaces(ctx context.Context, in *VMIdentifier, opts ...grpc.CallOption) (*GuestNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GuestNetworkResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_GuestGetNetworkInterfaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) GetBandwidthUsage(ctx context.Context, in *VMIdentifier, opts ...grpc.CallOption) (*BandwidthUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BandwidthUsageResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_GetBandwidthUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) SetBandwidthLimit(ctx context.Context, in *BandwidthLimitRequest, opts ...grpc.CallOption) (*VMOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMOperationResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_SetBandwidthLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) ResetBandwidthCounters(ctx context.Context, in *VMIdentifier, opts ...grpc.CallOption) (*VMOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMOperationResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_ResetBandwidthCounters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentServiceClient) GetNodeHealth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeHealthResponse)
	err := c.cc.Invoke(ctx, NodeAgentService_GetNodeHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeAgentServiceServer is the server API for NodeAgentService service.
// All implementations must embed UnimplementedNodeAgentServiceServer
// for forward compatibility.
//
// NodeAgentService provides VM lifecycle management and monitoring capabilities
// for a single compute node in the VirtueStack cluster.
type NodeAgentServiceServer interface {
	// CreateVM provisions a new virtual machine with the specified configuration.
	// This includes disk provisioning from a template and network configuration.
	CreateVM(context.Context, *CreateVMRequest) (*CreateVMResponse, error)
	// StartVM powers on a stopped virtual machine.
	// The VM must be in STOPPED or CRASHED state to be started.
	StartVM(context.Context, *VMIdentifier) (*VMOperationResponse, error)
	// StopVM gracefully shuts down a running virtual machine using ACPI.
	// The operation will wait for the specified timeout before returning.
	StopVM(context.Context, *StopVMRequest) (*VMOperationResponse, error)
	// ForceStopVM immediately terminates a virtual machine (power off).
	// Use with caution as this may cause data loss.
	ForceStopVM(context.Context, *VMIdentifier) (*VMOperationResponse, error)
	// DeleteVM permanently removes a virtual machine and its disk image.
	// The VM must be stopped before deletion.
	DeleteVM(context.Context, *DeleteVMRequest) (*VMOperationResponse, error)
	// ReinstallVM reimages a virtual machine from a new template.
	// All existing data on the VM will be lost.
	ReinstallVM(context.Context, *ReinstallVMRequest) (*CreateVMResponse, error)
	// ResizeVM modifies the resource allocation for a virtual machine.
	// Some changes may require a VM restart to take effect.
	ResizeVM(context.Context, *ResizeVMRequest) (*VMOperationResponse, error)
	// MigrateVM transfers a running VM to another compute node.
	// Supports both live migration and offline migration.
	MigrateVM(context.Context, *MigrateVMRequest) (*MigrateVMResponse, error)
	// AbortMigration cancels an in-progress VM migration.
	// The VM will remain on the source node.
	AbortMigration(context.Context, *VMIdentifier) (*VMOperationResponse, error)
	// Post-migration hook for bandwidth re-application
	PostMigrateSetup(context.Context, *PostMigrateSetupRequest) (*VMOperationResponse, error)
	// Create a point-in-time snapshot of a VM disk for migration.
	CreateDiskSnapshot(context.Context, *CreateDiskSnapshotRequest) (*CreateDiskSnapshotResponse, error)
	// Remove a disk snapshot created during migration.
	DeleteDiskSnapshot(context.Context, *DeleteDiskSnapshotRequest) (*VMOperationResponse, error)
	// Transfer a disk from this node to a target node (streaming).
	TransferDisk(*TransferDiskRequest, grpc.ServerStreamingServer[DiskChunk]) error
	// Receive a disk transfer from a source node (streaming).
	ReceiveDisk(grpc.ClientStreamingServer[DiskChunk, ReceiveDiskResponse]) error
	// Prepare a VM on this node using a transferred disk.
	PrepareMigratedVM(context.Context, *PrepareMigratedVMRequest) (*VMOperationResponse, error)
	// CreateLVMBackup creates a sparse backup file from an LVM thin snapshot.
	// Used for LVM VM backup operations.
	CreateLVMBackup(context.Context, *CreateLVMBackupRequest) (*CreateLVMBackupResponse, error)
	// RestoreLVMBackup restores an LVM thin LV from a backup file.
	// The thin LV must already exist; this overwrites it in-place.
	RestoreLVMBackup(context.Context, *RestoreLVMBackupRequest) (*VMOperationResponse, error)
	// StreamVNCConsole establishes a bidirectional VNC console stream.
	// Used for graphical console access to the VM.
	StreamVNCConsole(grpc.BidiStreamingServer[VNCFrame, VNCFrame]) error
	// StreamSerialConsole establishes a bidirectional serial console stream.
	// Used for text-based console access to the VM.
	StreamSerialConsole(grpc.BidiStreamingServer[SerialData, SerialData]) error
	// GetVMStatus retrieves the current operational state of a virtual machine.
	GetVMStatus(context.Context, *VMIdentifier) (*VMStatusResponse, error)
	// GetVMMetrics retrieves real-time resource utilization metrics for a VM.
	GetVMMetrics(context.Context, *VMIdentifier) (*VMMetricsResponse, error)
	// GetNodeResources retrieves aggregate resource information for the node.
	GetNodeResources(context.Context, *Empty) (*NodeResourcesResponse, error)
	// CreateSnapshot creates a point-in-time snapshot of a VM's disk.
	// The VM can be running or stopped during snapshot creation.
	CreateSnapshot(context.Context, *SnapshotRequest) (*Snapshot, error)
	// DeleteSnapshot removes a previously created disk snapshot.
	DeleteSnapshot(context.Context, *SnapshotIdentifier) (*VMOperationResponse, error)
	// RevertSnapshot restores a VM to a previous snapshot state.
	// The VM must be stopped before reverting.
	RevertSnapshot(context.Context, *SnapshotIdentifier) (*VMOperationResponse, error)
	// ListSnapshots retrieves all snapshots for a given virtual machine.
	ListSnapshots(context.Context, *VMIdentifier) (*SnapshotListResponse, error)
	// GuestExecCommand executes a command inside the VM via the QEMU guest agent.
	// Requires the guest agent to be installed and running in the VM.
	GuestExecCommand(context.Context, *GuestExecRequest) (*GuestExecResponse, error)
	// GuestSetPassword changes a user password inside the VM.
	// Requires the QEMU guest agent to be installed and running.
	GuestSetPassword(context.Context, *GuestPasswordRequest) (*VMOperationResponse, error)
	// GuestFreezeFilesystems freezes all filesystems in the VM.
	// Used for consistent backup operations.
	GuestFreezeFilesystems(context.Context, *VMIdentifier) (*VMOperationResponse, error)
	// GuestThawFilesystems unfreezes all filesystems in the VM.
	// Used after backup operations are complete.
	GuestThawFilesystems(context.Context, *VMIdentifier) (*VMOperationResponse, error)
	// GuestGetNetworkInterfaces retrieves network interface information from the VM.
	// Requires the QEMU guest agent to be installed and running.
	GuestGetNetworkInterfaces(context.Context, *VMIdentifier) (*GuestNetworkResponse, error)
	// GetBandwidthUsage retrieves current network bandwidth usage for a VM.
	GetBandwidthUsage(context.Context, *VMIdentifier) (*BandwidthUsageResponse, error)
	// SetBandwidthLimit applies a bandwidth cap to a VM's network interface.
	SetBandwidthLimit(context.Context, *BandwidthLimitRequest) (*VMOperationResponse, error)
	// ResetBandwidthCounters resets the bandwidth usage counters for a VM.
	ResetBandwidthCounters(context.Context, *VMIdentifier) (*VMOperationResponse, error)
	// Ping verifies the node agent service is responsive.
	Ping(context.Context, *Empty) (*PingResponse, error)
	// GetNodeHealth retrieves comprehensive health status of the node.
	GetNodeHealth(context.Context, *Empty) (*NodeHealthResponse, error)
	mustEmbedUnimplementedNodeAgentServiceServer()
}

// UnimplementedNodeAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeAgentServiceServer struct{}

func (UnimplementedNodeAgentServiceServer) CreateVM(context.Context, *CreateVMRequest) (*CreateVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVM not implemented")
}
func (UnimplementedNodeAgentServiceServer) StartVM(context.Context, *VMIdentifier) (*VMOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartVM not implemented")
}
func (UnimplementedNodeAgentServiceServer) StopVM(context.Context, *StopVMRequest) (*VMOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopVM not implemented")
}
func (UnimplementedNodeAgentServiceServer) ForceStopVM(context.Context, *VMIdentifier) (*VMOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForceStopVM not implemented")
}
func (UnimplementedNodeAgentServiceServer) DeleteVM(context.Context, *DeleteVMRequest) (*VMOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVM not implemented")
}
func (UnimplementedNodeAgentServiceServer) ReinstallVM(context.Context, *ReinstallVMRequest) (*CreateVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReinstallVM not implemented")
}
func (UnimplementedNodeAgentServiceServer) ResizeVM(context.Context, *ResizeVMRequest) (*VMOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResizeVM not implemented")
}
func (UnimplementedNodeAgentServiceServer) MigrateVM(context.Context, *MigrateVMRequest) (*MigrateVMResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MigrateVM not implemented")
}
func (UnimplementedNodeAgentServiceServer) AbortMigration(context.Context, *VMIdentifier) (*VMOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AbortMigration not implemented")
}
func (UnimplementedNodeAgentServiceServer) PostMigrateSetup(context.Context, *PostMigrateSetupRequest) (*VMOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PostMigrateSetup not implemented")
}
func (UnimplementedNodeAgentServiceServer) CreateDiskSnapshot(context.Context, *CreateDiskSnapshotRequest) (*CreateDiskSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDiskSnapshot not implemented")
}
func (UnimplementedNodeAgentServiceServer) DeleteDiskSnapshot(context.Context, *DeleteDiskSnapshotRequest) (*VMOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDiskSnapshot not implemented")
}
func (UnimplementedNodeAgentServiceServer) TransferDisk(*TransferDiskRequest, grpc.ServerStreamingServer[DiskChunk]) error {
	return status.Error(codes.Unimplemented, "method TransferDisk not implemented")
}
func (UnimplementedNodeAgentServiceServer) ReceiveDisk(grpc.ClientStreamingServer[DiskChunk, ReceiveDiskResponse]) error {
	return status.Error(codes.Unimplemented, "method ReceiveDisk not implemented")
}
func (UnimplementedNodeAgentServiceServer) PrepareMigratedVM(context.Context, *PrepareMigratedVMRequest) (*VMOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareMigratedVM not implemented")
}
func (UnimplementedNodeAgentServiceServer) CreateLVMBackup(context.Context, *CreateLVMBackupRequest) (*CreateLVMBackupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLVMBackup not implemented")
}
func (UnimplementedNodeAgentServiceServer) RestoreLVMBackup(context.Context, *RestoreLVMBackupRequest) (*VMOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreLVMBackup not implemented")
}
func (UnimplementedNodeAgentServiceServer) StreamVNCConsole(grpc.BidiStreamingServer[VNCFrame, VNCFrame]) error {
	return status.Error(codes.Unimplemented, "method StreamVNCConsole not implemented")
}
func (UnimplementedNodeAgentServiceServer) StreamSerialConsole(grpc.BidiStreamingServer[SerialData, SerialData]) error {
	return status.Error(codes.Unimplemented, "method StreamSerialConsole not implemented")
}
func (UnimplementedNodeAgentServiceServer) GetVMStatus(context.Context, *VMIdentifier) (*VMStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVMStatus not implemented")
}
func (UnimplementedNodeAgentServiceServer) GetVMMetrics(context.Context, *VMIdentifier) (*VMMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVMMetrics not implemented")
}
func (UnimplementedNodeAgentServiceServer) GetNodeResources(context.Context, *Empty) (*NodeResourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeResources not implemented")
}
func (UnimplementedNodeAgentServiceServer) CreateSnapshot(context.Context, *SnapshotRequest) (*Snapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSnapshot not implemented")
}
func (UnimplementedNodeAgentServiceServer) DeleteSnapshot(context.Context, *SnapshotIdentifier) (*VMOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSnapshot not implemented")
}
func (UnimplementedNodeAgentServiceServer) RevertSnapshot(context.Context, *SnapshotIdentifier) (*VMOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevertSnapshot not implemented")
}
func (UnimplementedNodeAgentServiceServer) ListSnapshots(context.Context, *VMIdentifier) (*SnapshotListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSnapshots not implemented")
}
func (UnimplementedNodeAgentServiceServer) GuestExecCommand(context.Context, *GuestExecRequest) (*GuestExecResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GuestExecCommand not implemented")
}
func (UnimplementedNodeAgentServiceServer) GuestSetPassword(context.Context, *GuestPasswordRequest) (*VMOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GuestSetPassword not implemented")
}
func (UnimplementedNodeAgentServiceServer) GuestFreezeFilesystems(context.Context, *VMIdentifier) (*VMOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GuestFreezeFilesystems not implemented")
}
func (UnimplementedNodeAgentServiceServer) GuestThawFilesystems(context.Context, *VMIdentifier) (*VMOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GuestThawFilesystems not implemented")
}
func (UnimplementedNodeAgentServiceServer) GuestGetNetworkInterfaces(context.Context, *VMIdentifier) (*GuestNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GuestGetNetworkInterfaces not implemented")
}
func (UnimplementedNodeAgentServiceServer) GetBandwidthUsage(context.Context, *VMIdentifier) (*BandwidthUsageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBandwidthUsage not implemented")
}
func (UnimplementedNodeAgentServiceServer) SetBandwidthLimit(context.Context, *BandwidthLimitRequest) (*VMOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetBandwidthLimit not implemented")
}
func (UnimplementedNodeAgentServiceServer) ResetBandwidthCounters(context.Context, *VMIdentifier) (*VMOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetBandwidthCounters not implemented")
}
func (UnimplementedNodeAgentServiceServer) Ping(context.Context, *Empty) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedNodeAgentServiceServer) GetNodeHealth(context.Context, *Empty) (*NodeHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeHealth not implemented")
}
func (UnimplementedNodeAgentServiceServer) mustEmbedUnimplementedNodeAgentServiceServer() {}
func (UnimplementedNodeAgentServiceServer) testEmbeddedByValue()                          {}

// UnsafeNodeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeAgentServiceServer will
// result in compilation errors.
type UnsafeNodeAgentServiceServer interface {
	mustEmbedUnimplementedNodeAgentServiceServer()
}

func RegisterNodeAgentServiceServer(s grpc.ServiceRegistrar, srv NodeAgentServiceServer) {
	// If the following call panics, it indicates UnimplementedNodeAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeAgentService_ServiceDesc, srv)
}

func _NodeAgentService_CreateVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).CreateVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_CreateVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).CreateVM(ctx, req.(*CreateVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_StartVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMIdentifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).StartVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_StartVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).StartVM(ctx, req.(*VMIdentifier))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_StopVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).StopVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_StopVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).StopVM(ctx, req.(*StopVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_ForceStopVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMIdentifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).ForceStopVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_ForceStopVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).ForceStopVM(ctx, req.(*VMIdentifier))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_DeleteVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).DeleteVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_DeleteVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).DeleteVM(ctx, req.(*DeleteVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_ReinstallVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReinstallVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).ReinstallVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_ReinstallVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).ReinstallVM(ctx, req.(*ReinstallVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_ResizeVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResizeVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).ResizeVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_ResizeVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).ResizeVM(ctx, req.(*ResizeVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_MigrateVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).MigrateVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_MigrateVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).MigrateVM(ctx, req.(*MigrateVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_AbortMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMIdentifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).AbortMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_AbortMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).AbortMigration(ctx, req.(*VMIdentifier))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_PostMigrateSetup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostMigrateSetupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).PostMigrateSetup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_PostMigrateSetup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).PostMigrateSetup(ctx, req.(*PostMigrateSetupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_CreateDiskSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDiskSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).CreateDiskSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_CreateDiskSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).CreateDiskSnapshot(ctx, req.(*CreateDiskSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_DeleteDiskSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDiskSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).DeleteDiskSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_DeleteDiskSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).DeleteDiskSnapshot(ctx, req.(*DeleteDiskSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_TransferDisk_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TransferDiskRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeAgentServiceServer).TransferDisk(m, &grpc.GenericServerStream[TransferDiskRequest, DiskChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgentService_TransferDiskServer = grpc.ServerStreamingServer[DiskChunk]

func _NodeAgentService_ReceiveDisk_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeAgentServiceServer).ReceiveDisk(&grpc.GenericServerStream[DiskChunk, ReceiveDiskResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgentService_ReceiveDiskServer = grpc.ClientStreamingServer[DiskChunk, ReceiveDiskResponse]

func _NodeAgentService_PrepareMigratedVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareMigratedVMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).PrepareMigratedVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_PrepareMigratedVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).PrepareMigratedVM(ctx, req.(*PrepareMigratedVMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_CreateLVMBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLVMBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).CreateLVMBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_CreateLVMBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).CreateLVMBackup(ctx, req.(*CreateLVMBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_RestoreLVMBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreLVMBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).RestoreLVMBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_RestoreLVMBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).RestoreLVMBackup(ctx, req.(*RestoreLVMBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_StreamVNCConsole_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeAgentServiceServer).StreamVNCConsole(&grpc.GenericServerStream[VNCFrame, VNCFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgentService_StreamVNCConsoleServer = grpc.BidiStreamingServer[VNCFrame, VNCFrame]

func _NodeAgentService_StreamSerialConsole_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeAgentServiceServer).StreamSerialConsole(&grpc.GenericServerStream[SerialData, SerialData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgentService_StreamSerialConsoleServer = grpc.BidiStreamingServer[SerialData, SerialData]

func _NodeAgentService_GetVMStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMIdentifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).GetVMStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_GetVMStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).GetVMStatus(ctx, req.(*VMIdentifier))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_GetVMMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMIdentifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).GetVMMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_GetVMMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).GetVMMetrics(ctx, req.(*VMIdentifier))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_GetNodeResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).GetNodeResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_GetNodeResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).GetNodeResources(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_CreateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).CreateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_CreateSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).CreateSnapshot(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_DeleteSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotIdentifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).DeleteSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_DeleteSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).DeleteSnapshot(ctx, req.(*SnapshotIdentifier))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_RevertSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotIdentifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).RevertSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_RevertSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).RevertSnapshot(ctx, req.(*SnapshotIdentifier))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_ListSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMIdentifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).ListSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_ListSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).ListSnapshots(ctx, req.(*VMIdentifier))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_GuestExecCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuestExecRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).GuestExecCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_GuestExecCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).GuestExecCommand(ctx, req.(*GuestExecRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_GuestSetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GuestPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).GuestSetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_GuestSetPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).GuestSetPassword(ctx, req.(*GuestPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_GuestFreezeFilesystems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMIdentifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).GuestFreezeFilesystems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_GuestFreezeFilesystems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).GuestFreezeFilesystems(ctx, req.(*VMIdentifier))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_GuestThawFilesystems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMIdentifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).GuestThawFilesystems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_GuestThawFilesystems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).GuestThawFilesystems(ctx, req.(*VMIdentifier))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_GuestGetNetworkInterfaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMIdentifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).GuestGetNetworkInterfaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_GuestGetNetworkInterfaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).GuestGetNetworkInterfaces(ctx, req.(*VMIdentifier))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_GetBandwidthUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMIdentifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).GetBandwidthUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_GetBandwidthUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).GetBandwidthUsage(ctx, req.(*VMIdentifier))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_SetBandwidthLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BandwidthLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).SetBandwidthLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_SetBandwidthLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).SetBandwidthLimit(ctx, req.(*BandwidthLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_ResetBandwidthCounters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMIdentifier)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).ResetBandwidthCounters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_ResetBandwidthCounters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).ResetBandwidthCounters(ctx, req.(*VMIdentifier))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgentService_GetNodeHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServiceServer).GetNodeHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgentService_GetNodeHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServiceServer).GetNodeHealth(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeAgentService_ServiceDesc is the grpc.ServiceDesc for NodeAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "virtuestack.nodeagent.NodeAgentService",
	HandlerType: (*NodeAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVM",
			Handler:    _NodeAgentService_CreateVM_Handler,
		},
		{
			MethodName: "StartVM",
			Handler:    _NodeAgentService_StartVM_Handler,
		},
		{
			MethodName: "StopVM",
			Handler:    _NodeAgentService_StopVM_Handler,
		},
		{
			MethodName: "ForceStopVM",
			Handler:    _NodeAgentService_ForceStopVM_Handler,
		},
		{
			MethodName: "DeleteVM",
			Handler:    _NodeAgentService_DeleteVM_Handler,
		},
		{
			MethodName: "ReinstallVM",
			Handler:    _NodeAgentService_ReinstallVM_Handler,
		},
		{
			MethodName: "ResizeVM",
			Handler:    _NodeAgentService_ResizeVM_Handler,
		},
		{
			MethodName: "MigrateVM",
			Handler:    _NodeAgentService_MigrateVM_Handler,
		},
		{
			MethodName: "AbortMigration",
			Handler:    _NodeAgentService_AbortMigration_Handler,
		},
		{
			MethodName: "PostMigrateSetup",
			Handler:    _NodeAgentService_PostMigrateSetup_Handler,
		},
		{
			MethodName: "CreateDiskSnapshot",
			Handler:    _NodeAgentService_CreateDiskSnapshot_Handler,
		},
		{
			MethodName: "DeleteDiskSnapshot",
			Handler:    _NodeAgentService_DeleteDiskSnapshot_Handler,
		},
		{
			MethodName: "PrepareMigratedVM",
			Handler:    _NodeAgentService_PrepareMigratedVM_Handler,
		},
		{
			MethodName: "CreateLVMBackup",
			Handler:    _NodeAgentService_CreateLVMBackup_Handler,
		},
		{
			MethodName: "RestoreLVMBackup",
			Handler:    _NodeAgentService_RestoreLVMBackup_Handler,
		},
		{
			MethodName: "GetVMStatus",
			Handler:    _NodeAgentService_GetVMStatus_Handler,
		},
		{
			MethodName: "GetVMMetrics",
			Handler:    _NodeAgentService_GetVMMetrics_Handler,
		},
		{
			MethodName: "GetNodeResources",
			Handler:    _NodeAgentService_GetNodeResources_Handler,
		},
		{
			MethodName: "CreateSnapshot",
			Handler:    _NodeAgentService_CreateSnapshot_Handler,
		},
		{
			MethodName: "DeleteSnapshot",
			Handler:    _NodeAgentService_DeleteSnapshot_Handler,
		},
		{
			MethodName: "RevertSnapshot",
			Handler:    _NodeAgentService_RevertSnapshot_Handler,
		},
		{
			MethodName: "ListSnapshots",
			Handler:    _NodeAgentService_ListSnapshots_Handler,
		},
		{
			MethodName: "GuestExecCommand",
			Handler:    _NodeAgentService_GuestExecCommand_Handler,
		},
		{
			MethodName: "GuestSetPassword",
			Handler:    _NodeAgentService_GuestSetPassword_Handler,
		},
		{
			MethodName: "GuestFreezeFilesystems",
			Handler:    _NodeAgentService_GuestFreezeFilesystems_Handler,
		},
		{
			MethodName: "GuestThawFilesystems",
			Handler:    _NodeAgentService_GuestThawFilesystems_Handler,
		},
		{
			MethodName: "GuestGetNetworkInterfaces",
			Handler:    _NodeAgentService_GuestGetNetworkInterfaces_Handler,
		},
		{
			MethodName: "GetBandwidthUsage",
			Handler:    _NodeAgentService_GetBandwidthUsage_Handler,
		},
		{
			MethodName: "SetBandwidthLimit",
			Handler:    _NodeAgentService_SetBandwidthLimit_Handler,
		},
		{
			MethodName: "ResetBandwidthCounters",
			Handler:    _NodeAgentService_ResetBandwidthCounters_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _NodeAgentService_Ping_Handler,
		},
		{
			MethodName: "GetNodeHealth",
			Handler:    _NodeAgentService_GetNodeHealth_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TransferDisk",
			Handler:       _NodeAgentService_TransferDisk_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReceiveDisk",
			Handler:       _NodeAgentService_ReceiveDisk_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamVNCConsole",
			Handler:       _NodeAgentService_StreamVNCConsole_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StreamSerialConsole",
			Handler:       _NodeAgentService_StreamSerialConsole_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "virtuestack/node_agent.proto",
}
