#!/bin/bash
# =============================================================================
# VirtueStack E2E Test Setup Script
# =============================================================================
# This script sets up the complete environment for E2E testing:
# - Generates test secrets
# - Seeds test data into the database
# - Creates test users (admin, customer)
# - Configures the Docker stack for testing
#
# Usage:
#   ./scripts/setup-e2e.sh           # Setup only
#   ./scripts/setup-e2e.sh --start   # Setup and start services
#   ./scripts/setup-e2e.sh --clean   # Clean up everything
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
DOCKER_COMPOSE=(docker compose --env-file .env.test -f docker-compose.yml -f docker-compose.test.yml)

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Test configuration
TEST_ADMIN_EMAIL="admin@test.virtuestack.local"
TEST_ADMIN_2FA_EMAIL="2fa-admin@test.virtuestack.local"
TEST_ADMIN_PASSWORD="AdminTest123!"
TEST_ADMIN_TOTP_SECRET="JBSWY3DPEHPK3PXP"

TEST_CUSTOMER_EMAIL="customer@test.virtuestack.local"
TEST_SECONDARY_CUSTOMER_EMAIL="test-customer@example.com"
TEST_CUSTOMER_2FA_EMAIL="2fa-customer@test.virtuestack.local"
TEST_CUSTOMER_PASSWORD="CustomerTest123!"
TEST_CUSTOMER_TOTP_SECRET="KRSXG5DSN5XW4ZLP"

TEST_STORAGE_BACKEND_CEPH_ID="eeeeeeee-eeee-eeee-eeee-eeeeeeee0001"
TEST_STORAGE_BACKEND_QCOW_ID="eeeeeeee-eeee-eeee-eeee-eeeeeeee0002"
TEST_STORAGE_BACKEND_LVM_ID="eeeeeeee-eeee-eeee-eeee-eeeeeeee0003"

# =============================================================================
# Helper Functions
# =============================================================================

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

require_commands() {
    local missing=()

    for cmd in "$@"; do
        if ! command -v "$cmd" >/dev/null 2>&1; then
            missing+=("$cmd")
        fi
    done

    if [ ${#missing[@]} -ne 0 ]; then
        log_error "Missing required tools: ${missing[*]}"
        exit 1
    fi
}

generate_random_string() {
    local length=${1:-32}
    openssl rand -base64 "$length" | tr -d '\n=' | cut -c1-"$length"
}

generate_random_hex() {
    local bytes=${1:-32}
    openssl rand -hex "$bytes" | tr -d '\n'
}

check_dependencies() {
    log_info "Checking dependencies..."
    require_commands openssl curl jq go
    log_success "All dependencies available"
}

load_env_file() {
    local env_file="${1:-${PROJECT_ROOT}/.env.test}"

    if [ ! -f "${env_file}" ]; then
        log_error "Environment file not found: ${env_file}"
        log_error "Run ./scripts/setup-e2e.sh first or create ${env_file} before using --seed-only"
        exit 1
    fi

    set -a
    # shellcheck disable=SC1090
    source "${env_file}"
    set +a
}

build_database_url() {
    local host="${POSTGRES_HOST:-localhost}"
    local port="${POSTGRES_PORT:-5432}"
    local sslmode="${POSTGRES_SSLMODE:-disable}"

    printf 'postgresql://%s:%s@%s:%s/%s?sslmode=%s' \
        "${POSTGRES_USER:-virtuestack}" \
        "${POSTGRES_PASSWORD}" \
        "${host}" \
        "${port}" \
        "${POSTGRES_DB:-virtuestack}" \
        "${sslmode}"
}

# =============================================================================
# Environment Setup
# =============================================================================

setup_env_file() {
    log_info "Creating .env.test file..."
    local env_file="${PROJECT_ROOT}/.env.test"

    (
        umask 077
        cat > "${env_file}" << EOF
# =============================================================================
# VirtueStack E2E Test Environment
# =============================================================================
# Generated by setup-e2e.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT USE IN PRODUCTION
# =============================================================================

# PostgreSQL
POSTGRES_USER=virtuestack
POSTGRES_PASSWORD=$(generate_random_hex 24)
POSTGRES_DB=virtuestack
POSTGRES_HOST=localhost
POSTGRES_PORT=5432
POSTGRES_SSLMODE=disable

# NATS
NATS_AUTH_TOKEN=$(generate_random_hex 24)

# JWT Configuration (32+ character secret)
JWT_SECRET=$(generate_random_string 64)

# Encryption Key (32 bytes, 64 hex characters)
ENCRYPTION_KEY=$(generate_random_hex 32)

# Guest operation HMAC secret (shared across controller and node agent)
GUEST_OP_HMAC_SECRET=$(generate_random_string 48)

# Logging
LOG_LEVEL=debug

# WebUI Configuration
NEXT_PUBLIC_API_URL=/api/v1
ADMIN_URL=http://localhost:3000
CUSTOMER_URL=http://localhost:3001
BASE_URL=http://localhost:8080

# Test Credentials
TEST_ADMIN_EMAIL=${TEST_ADMIN_EMAIL}
TEST_ADMIN_2FA_EMAIL=${TEST_ADMIN_2FA_EMAIL}
TEST_ADMIN_PASSWORD=${TEST_ADMIN_PASSWORD}
TEST_ADMIN_TOTP_SECRET=${TEST_ADMIN_TOTP_SECRET}

TEST_CUSTOMER_EMAIL=${TEST_CUSTOMER_EMAIL}
TEST_CUSTOMER_2FA_EMAIL=${TEST_CUSTOMER_2FA_EMAIL}
TEST_CUSTOMER_PASSWORD=${TEST_CUSTOMER_PASSWORD}
TEST_CUSTOMER_TOTP_SECRET=${TEST_CUSTOMER_TOTP_SECRET}

# Storage (for Node Agent testing)
STORAGE_BACKEND=ceph
CEPH_POOL=vs-vms
CEPH_USER=virtuestack

# SSL (self-signed for testing)
SSL_CERT_PATH=./ssl/cert.pem
SSL_KEY_PATH=./ssl/key.pem
EOF
    )
    chmod 600 "${PROJECT_ROOT}/.env.test"

    log_success "Created .env.test"
}

# =============================================================================
# SSL Certificate Generation
# =============================================================================

generate_ssl_certs() {
    log_info "Generating SSL certificates for testing..."

    local ssl_dir="${PROJECT_ROOT}/ssl"
    mkdir -p "$ssl_dir"

    # Generate self-signed certificate
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout "${ssl_dir}/key.pem" \
        -out "${ssl_dir}/cert.pem" \
        -subj "/C=US/ST=Test/L=Test/O=VirtueStack/OU=Testing/CN=localhost" \
        -addext "subjectAltName=DNS:localhost,DNS:*.localhost,IP:127.0.0.1" \
        2>/dev/null

    # Keep the private key owner-only. The nginx master process loads the key
    # before dropping privileges to its worker user.
    chmod 600 "${ssl_dir}/key.pem"
    chmod 644 "${ssl_dir}/cert.pem"

    log_success "Generated SSL certificates"
}

# =============================================================================
# mTLS Certificate Generation
# =============================================================================

generate_mtls_certs() {
    log_info "Generating mTLS certificates for Controller-Node Agent communication..."

    local certs_dir="${PROJECT_ROOT}/certs"
    mkdir -p "$certs_dir"

    # Generate CA
    openssl genrsa -out "${certs_dir}/ca.key" 4096 2>/dev/null
    openssl req -new -x509 -days 365 -key "${certs_dir}/ca.key" \
        -out "${certs_dir}/ca.crt" \
        -subj "/C=US/ST=Test/L=Test/O=VirtueStack/OU=CA/CN=VirtueStack Test CA" \
        2>/dev/null

    # Generate Controller certificate
    openssl genrsa -out "${certs_dir}/controller.key" 4096 2>/dev/null
    openssl req -new -key "${certs_dir}/controller.key" \
        -out "${certs_dir}/controller.csr" \
        -subj "/C=US/ST=Test/L=Test/O=VirtueStack/OU=Controller/CN=controller" \
        2>/dev/null
    openssl x509 -req -days 365 -in "${certs_dir}/controller.csr" \
        -CA "${certs_dir}/ca.crt" -CAkey "${certs_dir}/ca.key" -CAcreateserial \
        -out "${certs_dir}/controller.crt" \
        -extfile <(echo "subjectAltName=DNS:controller,DNS:localhost,IP:127.0.0.1") \
        2>/dev/null
    rm -f "${certs_dir}/controller.csr"

    # Generate Node Agent certificate
    openssl genrsa -out "${certs_dir}/node-agent.key" 4096 2>/dev/null
    openssl req -new -key "${certs_dir}/node-agent.key" \
        -out "${certs_dir}/node-agent.csr" \
        -subj "/C=US/ST=Test/L=Test/O=VirtueStack/OU=Node Agent/CN=node-agent" \
        2>/dev/null
    openssl x509 -req -days 365 -in "${certs_dir}/node-agent.csr" \
        -CA "${certs_dir}/ca.crt" -CAkey "${certs_dir}/ca.key" -CAcreateserial \
        -out "${certs_dir}/node-agent.crt" \
        -extfile <(echo "subjectAltName=DNS:node-agent,DNS:localhost,IP:127.0.0.1") \
        2>/dev/null
    rm -f "${certs_dir}/node-agent.csr"

    # Set permissions
    chmod 600 "${certs_dir}"/*.key
    chmod 644 "${certs_dir}"/*.crt

    log_success "Generated mTLS certificates"
}

# =============================================================================
# Database Seed Data
# =============================================================================

create_seed_sql() {
    log_info "Creating database seed SQL..."

    local seed_file="${PROJECT_ROOT}/migrations/test_seed.sql"
    local seed_materials_file
    local admin_password_hash
    local customer_password_hash
    local admin_totp_encrypted
    local customer_totp_encrypted
    local webhook_secret_encrypted
    local primary_api_key_hash
    local secondary_api_key_hash

    load_env_file
    seed_materials_file="$(mktemp "${PROJECT_ROOT}/migrations/test_seed_materials.XXXXXX.json")"

    local generator_file
    generator_file="$(mktemp "${PROJECT_ROOT}/.e2e-seed-generator-XXXXXX.go")"

    cat > "${generator_file}" <<'EOF'
package main

import (
	"encoding/json"
	"log"
	"os"

	"github.com/alexedwards/argon2id"

	sharedcrypto "github.com/AbuGosok/VirtueStack/internal/shared/crypto"
)

type seedMaterials struct {
	AdminPasswordHash     string `json:"admin_password_hash"`
	CustomerPasswordHash  string `json:"customer_password_hash"`
	AdminTOTPEncrypted    string `json:"admin_totp_encrypted"`
	CustomerTOTPEncrypted string `json:"customer_totp_encrypted"`
	WebhookSecretEncrypted string `json:"webhook_secret_encrypted"`
	PrimaryAPIKeyHash     string `json:"primary_api_key_hash"`
	SecondaryAPIKeyHash   string `json:"secondary_api_key_hash"`
}

func envOrDie(key string) string {
	value := os.Getenv(key)
	if value == "" {
		log.Fatalf("%s must be set", key)
	}
	return value
}

func mustHash(password string) string {
	hash, err := argon2id.CreateHash(password, &argon2id.Params{
		Memory:      64 * 1024,
		Iterations:  3,
		Parallelism: 4,
		SaltLength:  16,
		KeyLength:   32,
	})
	if err != nil {
		log.Fatalf("hash password: %v", err)
	}
	return hash
}

func mustEncrypt(plaintext, hexKey string) string {
	ciphertext, err := sharedcrypto.Encrypt(plaintext, hexKey)
	if err != nil {
		log.Fatalf("encrypt secret: %v", err)
	}
	return ciphertext
}

func main() {
	encryptionKey := envOrDie("ENCRYPTION_KEY")
	adminPassword := envOrDie("TEST_ADMIN_PASSWORD")
	customerPassword := envOrDie("TEST_CUSTOMER_PASSWORD")
	adminTOTP := envOrDie("TEST_ADMIN_TOTP_SECRET")
	customerTOTP := envOrDie("TEST_CUSTOMER_TOTP_SECRET")

	materials := seedMaterials{
		AdminPasswordHash:      mustHash(adminPassword),
		CustomerPasswordHash:   mustHash(customerPassword),
		AdminTOTPEncrypted:     mustEncrypt(adminTOTP, encryptionKey),
		CustomerTOTPEncrypted:  mustEncrypt(customerTOTP, encryptionKey),
		WebhookSecretEncrypted: mustEncrypt("vs-e2e-webhook-secret", encryptionKey),
		PrimaryAPIKeyHash:      sharedcrypto.GenerateHMACSignature(encryptionKey, []byte("vs-e2e-key-primary")),
		SecondaryAPIKeyHash:    sharedcrypto.GenerateHMACSignature(encryptionKey, []byte("vs-e2e-key-secondary")),
	}

	encoder := json.NewEncoder(os.Stdout)
	encoder.SetIndent("", "  ")
	if err := encoder.Encode(materials); err != nil {
		log.Fatalf("encode seed materials: %v", err)
	}
}
EOF

    (
        cd "${PROJECT_ROOT}"
        go run "${generator_file}" > "${seed_materials_file}"
    )
    rm -f "${generator_file}"

    admin_password_hash="$(jq -r '.admin_password_hash' "${seed_materials_file}")"
    customer_password_hash="$(jq -r '.customer_password_hash' "${seed_materials_file}")"
    admin_totp_encrypted="$(jq -r '.admin_totp_encrypted' "${seed_materials_file}")"
    customer_totp_encrypted="$(jq -r '.customer_totp_encrypted' "${seed_materials_file}")"
    webhook_secret_encrypted="$(jq -r '.webhook_secret_encrypted' "${seed_materials_file}")"
    primary_api_key_hash="$(jq -r '.primary_api_key_hash' "${seed_materials_file}")"
    secondary_api_key_hash="$(jq -r '.secondary_api_key_hash' "${seed_materials_file}")"
    rm -f "${seed_materials_file}"

    cat > "${seed_file}" <<EOF
-- =============================================================================
-- VirtueStack E2E Test Seed Data
-- =============================================================================
-- Generated by scripts/setup-e2e.sh against the current schema contract.
-- Uses node_storage + explicit storage_backend_id, encrypted secrets, and
-- HMAC-hashed customer API keys to match production behavior.
-- =============================================================================

BEGIN;
SET lock_timeout = '5s';

DELETE FROM webhook_deliveries
WHERE webhook_id IN (
    SELECT id FROM webhooks
    WHERE customer_id IN (
        '88888888-8888-8888-8888-888888888001',
        '88888888-8888-8888-8888-888888888002',
        '88888888-8888-8888-8888-888888888003'
    )
);
DELETE FROM webhooks
WHERE customer_id IN (
    '88888888-8888-8888-8888-888888888001',
    '88888888-8888-8888-8888-888888888002',
    '88888888-8888-8888-8888-888888888003'
);
DELETE FROM customer_api_keys
WHERE customer_id IN (
    '88888888-8888-8888-8888-888888888001',
    '88888888-8888-8888-8888-888888888002',
    '88888888-8888-8888-8888-888888888003'
);
DELETE FROM snapshots WHERE id IN (
    'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb01',
    'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb02',
    'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb03'
);
DELETE FROM backups WHERE id IN (
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa01',
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa02',
    'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa03'
);
DELETE FROM ip_addresses WHERE ip_set_id IN (
    '44444444-4444-4444-4444-444444444001',
    '44444444-4444-4444-4444-444444444002'
);
DELETE FROM vms WHERE id IN (
    '99999999-9999-9999-9999-999999999001',
    '99999999-9999-9999-9999-999999999002',
    '99999999-9999-9999-9999-999999999003'
);
DELETE FROM node_storage WHERE node_id IN (
    '33333333-3333-3333-3333-333333333001',
    '33333333-3333-3333-3333-333333333002',
    '33333333-3333-3333-3333-333333333003',
    '33333333-3333-3333-3333-333333333004',
    '33333333-3333-3333-3333-333333333005'
) OR storage_backend_id IN (
    '${TEST_STORAGE_BACKEND_CEPH_ID}',
    '${TEST_STORAGE_BACKEND_QCOW_ID}',
    '${TEST_STORAGE_BACKEND_LVM_ID}'
);
DELETE FROM storage_backends WHERE id IN (
    '${TEST_STORAGE_BACKEND_CEPH_ID}',
    '${TEST_STORAGE_BACKEND_QCOW_ID}',
    '${TEST_STORAGE_BACKEND_LVM_ID}'
);
DELETE FROM templates WHERE id IN (
    '66666666-6666-6666-6666-666666666001',
    '66666666-6666-6666-6666-666666666002',
    '66666666-6666-6666-6666-666666666003',
    '66666666-6666-6666-6666-666666666004',
    '66666666-6666-6666-6666-666666666005'
);
DELETE FROM ip_sets WHERE id IN (
    '44444444-4444-4444-4444-444444444001',
    '44444444-4444-4444-4444-444444444002'
);
DELETE FROM nodes WHERE id IN (
    '33333333-3333-3333-3333-333333333001',
    '33333333-3333-3333-3333-333333333002',
    '33333333-3333-3333-3333-333333333003',
    '33333333-3333-3333-3333-333333333004',
    '33333333-3333-3333-3333-333333333005'
);
DELETE FROM email_verification_tokens WHERE customer_id IN (
    '88888888-8888-8888-8888-888888888001',
    '88888888-8888-8888-8888-888888888002',
    '88888888-8888-8888-8888-888888888003'
);
DELETE FROM password_resets WHERE user_id IN (
    '77777777-7777-7777-7777-777777777001',
    '77777777-7777-7777-7777-777777777002',
    '77777777-7777-7777-7777-777777777003',
    '88888888-8888-8888-8888-888888888001',
    '88888888-8888-8888-8888-888888888002',
    '88888888-8888-8888-8888-888888888003'
);
DELETE FROM sessions WHERE user_id IN (
    '77777777-7777-7777-7777-777777777001',
    '77777777-7777-7777-7777-777777777002',
    '77777777-7777-7777-7777-777777777003'
) AND user_type = 'admin';
DELETE FROM sessions WHERE user_id IN (
    '88888888-8888-8888-8888-888888888001',
    '88888888-8888-8888-8888-888888888002',
    '88888888-8888-8888-8888-888888888003'
) AND user_type = 'customer';
DELETE FROM customers WHERE id IN (
    '88888888-8888-8888-8888-888888888001',
    '88888888-8888-8888-8888-888888888002',
    '88888888-8888-8888-8888-888888888003'
);
DELETE FROM admins WHERE id IN (
    '77777777-7777-7777-7777-777777777001',
    '77777777-7777-7777-7777-777777777002',
    '77777777-7777-7777-7777-777777777003'
);
DELETE FROM plans WHERE id IN (
    '11111111-1111-1111-1111-111111111001',
    '11111111-1111-1111-1111-111111111002',
    '11111111-1111-1111-1111-111111111003',
    '11111111-1111-1111-1111-111111111004'
);
DELETE FROM locations WHERE id IN (
    '22222222-2222-2222-2222-222222222001',
    '22222222-2222-2222-2222-222222222002'
);

INSERT INTO locations (id, name, region, country, created_at)
VALUES
    ('22222222-2222-2222-2222-222222222001', 'US East', 'us-east', 'US', NOW()),
    ('22222222-2222-2222-2222-222222222002', 'US West', 'us-west', 'US', NOW());

INSERT INTO plans (
    id, name, slug, vcpu, memory_mb, disk_gb, bandwidth_limit_gb, port_speed_mbps,
    price_monthly, price_hourly, price_hourly_stopped, currency,
    storage_backend, is_active, sort_order, snapshot_limit, backup_limit, iso_upload_limit,
    created_at, updated_at
) VALUES
    ('11111111-1111-1111-1111-111111111001', 'Basic Plan', 'basic-plan', 1, 1024, 20, 1000, 100, 500, 1, 0, 'USD', 'ceph', TRUE, 0, 2, 2, 2, NOW(), NOW()),
    ('11111111-1111-1111-1111-111111111002', 'Standard Plan', 'standard-plan', 2, 2048, 40, 2000, 500, 1000, 2, 1, 'USD', 'ceph', TRUE, 1, 3, 3, 3, NOW(), NOW()),
    ('11111111-1111-1111-1111-111111111003', 'Premium Plan', 'premium-plan', 4, 4096, 80, 4000, 1000, 2500, 4, 2, 'USD', 'ceph', TRUE, 2, 5, 5, 5, NOW(), NOW()),
    ('11111111-1111-1111-1111-111111111004', 'Enterprise Plan', 'enterprise-plan', 4, 4096, 80, 4000, 1000, 3000, 5, 2, 'USD', 'qcow', TRUE, 3, 5, 5, 5, NOW(), NOW());

INSERT INTO storage_backends (
    id, name, type, ceph_pool, ceph_user, ceph_monitors,
    storage_path, lvm_volume_group, lvm_thin_pool, health_status,
    created_at, updated_at
) VALUES
    ('${TEST_STORAGE_BACKEND_CEPH_ID}', 'Primary Ceph Cluster', 'ceph', 'vs-vms', 'virtuestack', 'ceph-mon-1:6789,ceph-mon-2:6789', NULL, NULL, NULL, 'healthy', NOW(), NOW()),
    ('${TEST_STORAGE_BACKEND_QCOW_ID}', 'Local QCOW Storage', 'qcow', NULL, NULL, NULL, '/var/lib/virtuestack/qcow', NULL, NULL, 'healthy', NOW(), NOW()),
    ('${TEST_STORAGE_BACKEND_LVM_ID}', 'LVM Thin Storage', 'lvm', NULL, NULL, NULL, NULL, 'vs-vg', 'thinpool', 'healthy', NOW(), NOW());

INSERT INTO nodes (
    id, hostname, grpc_address, management_ip, location_id, status,
    total_vcpu, total_memory_mb, allocated_vcpu, allocated_memory_mb,
    ceph_pool, storage_backend, storage_path, created_at
) VALUES
    ('33333333-3333-3333-3333-333333333001', 'test-node-1', 'mock-node-agent:50051', '10.0.0.101', '22222222-2222-2222-2222-222222222001', 'online', 32, 65536, 0, 0, 'vs-vms', 'ceph', NULL, NOW()),
    ('33333333-3333-3333-3333-333333333002', 'test-node-2', 'mock-node-agent:50051', '10.0.0.102', '22222222-2222-2222-2222-222222222001', 'online', 32, 65536, 0, 0, 'vs-vms', 'ceph', NULL, NOW()),
    ('33333333-3333-3333-3333-333333333003', 'test-node-3', 'mock-node-agent:50051', '10.0.0.103', '22222222-2222-2222-2222-222222222002', 'online', 24, 49152, 0, 0, NULL, 'qcow', '/var/lib/virtuestack/qcow', NOW()),
    ('33333333-3333-3333-3333-333333333004', 'test-node-4', 'mock-node-agent:50051', '10.0.0.104', '22222222-2222-2222-2222-222222222001', 'offline', 16, 32768, 0, 0, 'vs-vms', 'ceph', NULL, NOW()),
    ('33333333-3333-3333-3333-333333333005', 'test-node-5', 'mock-node-agent:50051', '10.0.0.105', '22222222-2222-2222-2222-222222222001', 'draining', 16, 32768, 0, 0, 'vs-vms', 'ceph', NULL, NOW());

INSERT INTO node_storage (node_id, storage_backend_id, enabled, preferred, created_at)
VALUES
    ('33333333-3333-3333-3333-333333333001', '${TEST_STORAGE_BACKEND_CEPH_ID}', TRUE, TRUE, NOW()),
    ('33333333-3333-3333-3333-333333333002', '${TEST_STORAGE_BACKEND_CEPH_ID}', TRUE, TRUE, NOW()),
    ('33333333-3333-3333-3333-333333333003', '${TEST_STORAGE_BACKEND_QCOW_ID}', TRUE, TRUE, NOW()),
    ('33333333-3333-3333-3333-333333333004', '${TEST_STORAGE_BACKEND_CEPH_ID}', TRUE, TRUE, NOW()),
    ('33333333-3333-3333-3333-333333333005', '${TEST_STORAGE_BACKEND_CEPH_ID}', TRUE, TRUE, NOW());

INSERT INTO ip_sets (id, name, location_id, network, gateway, ip_version, node_ids, created_at)
VALUES
    (
        '44444444-4444-4444-4444-444444444001',
        'Public IPv4 Pool',
        '22222222-2222-2222-2222-222222222001',
        '198.51.100.0/24',
        '198.51.100.1',
        4,
        ARRAY[
            '33333333-3333-3333-3333-333333333001',
            '33333333-3333-3333-3333-333333333002',
            '33333333-3333-3333-3333-333333333004',
            '33333333-3333-3333-3333-333333333005'
        ]::uuid[],
        NOW()
    ),
    (
        '44444444-4444-4444-4444-444444444002',
        'Private IPv4 Pool',
        '22222222-2222-2222-2222-222222222001',
        '10.10.0.0/24',
        '10.10.0.1',
        4,
        ARRAY[
            '33333333-3333-3333-3333-333333333001',
            '33333333-3333-3333-3333-333333333002'
        ]::uuid[],
        NOW()
    );

INSERT INTO ip_addresses (id, ip_set_id, address, ip_version, status, created_at)
SELECT
    '55555555-5555-5555-5555-' || LPAD((i + 1)::text, 12, '0'),
    '44444444-4444-4444-4444-444444444001',
    ('198.51.100.' || (10 + i)::text)::inet,
    4,
    'available',
    NOW()
FROM generate_series(0, 9) AS i;

INSERT INTO ip_addresses (id, ip_set_id, address, ip_version, status, created_at)
SELECT
    '55555555-5555-5555-5556-' || LPAD((i + 1)::text, 12, '0'),
    '44444444-4444-4444-4444-444444444002',
    ('10.10.0.' || (10 + i)::text)::inet,
    4,
    'available',
    NOW()
FROM generate_series(0, 4) AS i;

INSERT INTO templates (
    id, name, os_family, os_version, rbd_image, rbd_snapshot,
    min_disk_gb, supports_cloudinit, is_active, sort_order,
    version, description, storage_backend, created_at, updated_at
) VALUES
    ('66666666-6666-6666-6666-666666666001', 'Ubuntu 22.04', 'ubuntu', '22.04', 'ubuntu-22.04-server', 'stable', 20, TRUE, TRUE, 0, 1, 'Ubuntu 22.04 LTS cloud image', 'ceph', NOW(), NOW()),
    ('66666666-6666-6666-6666-666666666002', 'Ubuntu 24.04', 'ubuntu', '24.04', 'ubuntu-24.04-server', 'stable', 20, TRUE, TRUE, 1, 1, 'Ubuntu 24.04 LTS cloud image', 'ceph', NOW(), NOW()),
    ('66666666-6666-6666-6666-666666666003', 'Debian 12', 'debian', '12', 'debian-12-server', 'stable', 20, TRUE, TRUE, 2, 1, 'Debian 12 cloud image', 'ceph', NOW(), NOW()),
    ('66666666-6666-6666-6666-666666666004', 'Rocky Linux 9', 'rocky', '9', 'rocky-9-server', 'stable', 20, TRUE, TRUE, 3, 1, 'Rocky Linux 9 cloud image', 'ceph', NOW(), NOW()),
    ('66666666-6666-6666-6666-666666666005', 'AlmaLinux 9', 'almalinux', '9', 'almalinux-9-server', 'stable', 20, TRUE, TRUE, 4, 1, 'AlmaLinux 9 cloud image', 'ceph', NOW(), NOW());

INSERT INTO admins (
    id, email, password_hash, name,
    totp_secret_encrypted, totp_enabled, totp_backup_codes_hash,
    role, max_sessions, permissions, created_at, updated_at
) VALUES
    ('77777777-7777-7777-7777-777777777001', '${TEST_ADMIN_EMAIL}', '${admin_password_hash}', 'Primary Admin', '${admin_totp_encrypted}', FALSE, ARRAY[]::text[], 'admin', 3, NULL, NOW(), NOW()),
    ('77777777-7777-7777-7777-777777777002', 'secondary-admin@test.virtuestack.local', '${admin_password_hash}', 'Secondary Admin', '${admin_totp_encrypted}', FALSE, ARRAY[]::text[], 'super_admin', 5, NULL, NOW(), NOW()),
    ('77777777-7777-7777-7777-777777777003', '${TEST_ADMIN_2FA_EMAIL}', '${admin_password_hash}', 'Admin With 2FA', '${admin_totp_encrypted}', TRUE, ARRAY[]::text[], 'admin', 3, NULL, NOW(), NOW());

INSERT INTO customers (
    id, email, password_hash, name, external_client_id, billing_provider, auth_provider,
    totp_secret_encrypted, totp_enabled, totp_backup_codes_hash, totp_backup_codes_shown,
    status, created_at, updated_at
) VALUES
    ('88888888-8888-8888-8888-888888888001', '${TEST_CUSTOMER_EMAIL}', '${customer_password_hash}', 'Primary Test Customer', 1001, 'native', 'local', NULL, FALSE, ARRAY[]::text[], FALSE, 'active', NOW(), NOW()),
    ('88888888-8888-8888-8888-888888888002', '${TEST_SECONDARY_CUSTOMER_EMAIL}', '${customer_password_hash}', 'Provisioning Test Customer', 1002, 'native', 'local', NULL, FALSE, ARRAY[]::text[], FALSE, 'active', NOW(), NOW()),
    ('88888888-8888-8888-8888-888888888003', '${TEST_CUSTOMER_2FA_EMAIL}', '${customer_password_hash}', 'Customer With 2FA', 1003, 'native', 'local', '${customer_totp_encrypted}', TRUE, ARRAY[]::text[], FALSE, 'active', NOW(), NOW());

INSERT INTO vms (
    id, customer_id, node_id, plan_id, hostname, status,
    vcpu, memory_mb, disk_gb, port_speed_mbps, bandwidth_limit_gb,
    bandwidth_used_bytes, bandwidth_reset_at, mac_address, template_id,
    libvirt_domain_name, root_password_encrypted, external_service_id,
    storage_backend, disk_path, ceph_pool, rbd_image, storage_backend_id,
    created_at, updated_at
) VALUES
    (
        '99999999-9999-9999-9999-999999999001',
        '88888888-8888-8888-8888-888888888001',
        '33333333-3333-3333-3333-333333333001',
        '11111111-1111-1111-1111-111111111002',
        'test-vm-running',
        'running',
        2, 2048, 40, 500, 2000,
        0, NOW(), '52:54:00:00:00:11', '66666666-6666-6666-6666-666666666001',
        'vs-test-vm1', NULL, 5001,
        'ceph', NULL, 'vs-vms', 'vm-99999999-9999-9999-9999-999999999001-disk0', '${TEST_STORAGE_BACKEND_CEPH_ID}',
        NOW(), NOW()
    ),
    (
        '99999999-9999-9999-9999-999999999002',
        '88888888-8888-8888-8888-888888888001',
        '33333333-3333-3333-3333-333333333001',
        '11111111-1111-1111-1111-111111111001',
        'test-vm-stopped',
        'stopped',
        1, 1024, 20, 100, 1000,
        0, NOW(), '52:54:00:00:00:12', '66666666-6666-6666-6666-666666666003',
        'vs-test-vm2', NULL, 5002,
        'ceph', NULL, 'vs-vms', 'vm-99999999-9999-9999-9999-999999999002-disk0', '${TEST_STORAGE_BACKEND_CEPH_ID}',
        NOW(), NOW()
    ),
    (
        '99999999-9999-9999-9999-999999999003',
        '88888888-8888-8888-8888-888888888002',
        '33333333-3333-3333-3333-333333333003',
        '11111111-1111-1111-1111-111111111004',
        'test-vm-provisioning',
        'provisioning',
        4, 4096, 80, 1000, 4000,
        0, NOW(), '52:54:00:00:00:13', '66666666-6666-6666-6666-666666666002',
        'vs-test-vm3', NULL, 5003,
        'qcow', '/var/lib/virtuestack/qcow/99999999-9999-9999-9999-999999999003.qcow2', NULL, NULL, '${TEST_STORAGE_BACKEND_QCOW_ID}',
        NOW(), NOW()
    );

INSERT INTO backups (id, vm_id, method, name, source, admin_schedule_id, storage_backend,
    rbd_snapshot, file_path, snapshot_name, storage_path, size_bytes,
    status, expires_at, created_at
) VALUES
    ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa01', '99999999-9999-9999-9999-999999999001', 'full', 'Nightly Full Backup', 'manual', NULL, 'ceph', 'vm1-full-backup-1', NULL, NULL, 'vs-backups/backup-01', 10737418240, 'completed', NOW() + INTERVAL '14 days', NOW() - INTERVAL '1 day'),
    ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa02', '99999999-9999-9999-9999-999999999001', 'full', 'Manual Restore Point', 'manual', NULL, 'ceph', 'vm1-full-backup-2', NULL, NULL, 'vs-backups/backup-02', 2147483648, 'completed', NOW() + INTERVAL '7 days', NOW() - INTERVAL '12 hours'),
    ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa03', '99999999-9999-9999-9999-999999999001', 'full', 'In Progress Backup', 'manual', NULL, 'ceph', NULL, NULL, NULL, NULL, NULL, 'creating', NULL, NOW() - INTERVAL '5 minutes');

INSERT INTO snapshots (id, vm_id, name, rbd_snapshot, size_bytes, created_at)
VALUES
    ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb01', '99999999-9999-9999-9999-999999999001', 'before-update', 'snap-before-update', 536870912, NOW() - INTERVAL '2 days'),
    ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb02', '99999999-9999-9999-9999-999999999001', 'daily-backup', 'snap-daily-backup', 268435456, NOW() - INTERVAL '1 day'),
    ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb03', '99999999-9999-9999-9999-999999999002', 'initial', 'snap-initial', 134217728, NOW() - INTERVAL '3 days');

INSERT INTO customer_api_keys (
    id, customer_id, name, key_hash, allowed_ips, vm_ids,
    permissions, last_used_at, created_at, revoked_at, expires_at
) VALUES
    (
        'cccccccc-cccc-cccc-cccc-cccccccccc01',
        '88888888-8888-8888-8888-888888888001',
        'Primary automation key',
        '${primary_api_key_hash}',
        ARRAY['127.0.0.1/32']::cidr[],
        ARRAY['99999999-9999-9999-9999-999999999001', '99999999-9999-9999-9999-999999999002']::uuid[],
        ARRAY['vm:read', 'vm:write', 'vm:power']::text[],
        NOW() - INTERVAL '1 hour',
        NOW() - INTERVAL '7 days',
        NULL,
        NOW() + INTERVAL '30 days'
    ),
    (
        'cccccccc-cccc-cccc-cccc-cccccccccc02',
        '88888888-8888-8888-8888-888888888001',
        'Read-only expired key',
        '${secondary_api_key_hash}',
        ARRAY['10.0.0.0/24']::cidr[],
        ARRAY['99999999-9999-9999-9999-999999999001']::uuid[],
        ARRAY['vm:read', 'backup:read']::text[],
        NOW() - INTERVAL '30 days',
        NOW() - INTERVAL '60 days',
        NULL,
        NOW() - INTERVAL '1 day'
    );

INSERT INTO webhooks (
    id, customer_id, url, secret_hash, events, active,
    fail_count, last_success_at, last_failure_at, created_at, updated_at
) VALUES
    (
        'dddddddd-dddd-dddd-dddd-dddddddddd01',
        '88888888-8888-8888-8888-888888888001',
        'https://webhook.example.com/test',
        '${webhook_secret_encrypted}',
        ARRAY['vm.created', 'vm.deleted', 'backup.completed']::text[],
        TRUE,
        0,
        NOW() - INTERVAL '1 day',
        NULL,
        NOW() - INTERVAL '7 days',
        NOW()
    );

UPDATE ip_addresses
SET vm_id = '99999999-9999-9999-9999-999999999001',
    customer_id = '88888888-8888-8888-8888-888888888001',
    is_primary = TRUE,
    rdns_hostname = 'vm1.test.virtuestack.local',
    status = 'assigned',
    assigned_at = NOW(),
    released_at = NULL,
    cooldown_until = NULL
WHERE address = '198.51.100.10';

UPDATE ip_addresses
SET vm_id = '99999999-9999-9999-9999-999999999001',
    customer_id = '88888888-8888-8888-8888-888888888001',
    is_primary = FALSE,
    rdns_hostname = NULL,
    status = 'assigned',
    assigned_at = NOW(),
    released_at = NULL,
    cooldown_until = NULL
WHERE address = '198.51.100.11';

UPDATE ip_addresses
SET vm_id = '99999999-9999-9999-9999-999999999002',
    customer_id = '88888888-8888-8888-8888-888888888001',
    is_primary = TRUE,
    rdns_hostname = 'vm2.test.virtuestack.local',
    status = 'assigned',
    assigned_at = NOW(),
    released_at = NULL,
    cooldown_until = NULL
WHERE address = '198.51.100.12';

COMMIT;

SELECT 'E2E Test Seed Data Loaded' AS status;
SELECT
    (SELECT COUNT(*) FROM plans WHERE id IN (
        '11111111-1111-1111-1111-111111111001',
        '11111111-1111-1111-1111-111111111002',
        '11111111-1111-1111-1111-111111111003',
        '11111111-1111-1111-1111-111111111004'
    )) AS seeded_plans,
    (SELECT COUNT(*) FROM nodes WHERE id IN (
        '33333333-3333-3333-3333-333333333001',
        '33333333-3333-3333-3333-333333333002',
        '33333333-3333-3333-3333-333333333003',
        '33333333-3333-3333-3333-333333333004',
        '33333333-3333-3333-3333-333333333005'
    )) AS seeded_nodes,
    (SELECT COUNT(*) FROM vms WHERE id IN (
        '99999999-9999-9999-9999-999999999001',
        '99999999-9999-9999-9999-999999999002',
        '99999999-9999-9999-9999-999999999003'
    )) AS seeded_vms,
    (SELECT COUNT(*) FROM customers WHERE id IN (
        '88888888-8888-8888-8888-888888888001',
        '88888888-8888-8888-8888-888888888002',
        '88888888-8888-8888-8888-888888888003'
    )) AS seeded_customers,
    (SELECT COUNT(*) FROM admins WHERE id IN (
        '77777777-7777-7777-7777-777777777001',
        '77777777-7777-7777-7777-777777777002',
        '77777777-7777-7777-7777-777777777003'
    )) AS seeded_admins;
EOF

    log_success "Created seed SQL: $seed_file"
}

run_seed_sql() {
    local seed_path="${1:-${PROJECT_ROOT}/migrations/test_seed.sql}"
    local database_url
    local container_database_url

    load_env_file
    database_url="$(build_database_url)"

    if command -v psql >/dev/null 2>&1; then
        psql "${database_url}" -v ON_ERROR_STOP=1 -f "${seed_path}"
        return
    fi

    require_commands docker
    container_database_url="postgresql://${POSTGRES_USER:-virtuestack}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-virtuestack}?sslmode=disable"
    docker run --rm \
        --network virtuestack-test-network \
        -v "${PROJECT_ROOT}/migrations:/migrations:ro" \
        postgres:18-alpine \
        psql "${container_database_url}" -v ON_ERROR_STOP=1 -f "/migrations/$(basename "${seed_path}")"
}

# =============================================================================
# Docker Services
# =============================================================================

start_docker_services() {
    log_info "Starting Docker services..."
    require_commands docker
    load_env_file

    cd "$PROJECT_ROOT"

    # Build images
    "${DOCKER_COMPOSE[@]}" build

    # Start services
    "${DOCKER_COMPOSE[@]}" up -d

    # Wait for services to be healthy
    log_info "Waiting for services to be healthy..."
    sleep 10

    # Check PostgreSQL
    for i in {1..30}; do
        if "${DOCKER_COMPOSE[@]}" exec -T postgres pg_isready -U "${POSTGRES_USER:-virtuestack}" -d "${POSTGRES_DB:-virtuestack}" 2>/dev/null; then
            log_success "PostgreSQL is ready"
            break
        fi
        sleep 1
    done

    # Check NATS
    for i in {1..30}; do
        if "${DOCKER_COMPOSE[@]}" exec -T nats wget --spider -q http://localhost:8222/healthz 2>/dev/null; then
            log_success "NATS is ready"
            break
        fi
        sleep 1
    done

    # Check Controller
    for i in {1..30}; do
        if curl -sf http://localhost:8080/health > /dev/null 2>&1; then
            log_success "Controller is ready"
            break
        fi
        sleep 1
    done

    # Run migrations
    log_info "Running database migrations..."
    docker run --rm --network virtuestack-test-network \
        --env-file "${PROJECT_ROOT}/.env.test" \
        -v "${PROJECT_ROOT}/migrations:/migrations:ro" \
        migrate/migrate:v4.19.0 \
        -path /migrations \
        -database "postgresql://${POSTGRES_USER:-virtuestack}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-virtuestack}?sslmode=disable" up

    # Seed test data
    log_info "Seeding test data..."
    "${DOCKER_COMPOSE[@]}" exec -T postgres \
        psql -U "${POSTGRES_USER:-virtuestack}" -d "${POSTGRES_DB:-virtuestack}" \
        -v ON_ERROR_STOP=1 -f /docker-entrypoint-initdb.d/migrations/test_seed.sql

    log_success "All services started and healthy"
}

stop_docker_services() {
    log_info "Stopping Docker services..."
    require_commands docker

    cd "$PROJECT_ROOT"
    "${DOCKER_COMPOSE[@]}" down -v

    log_success "Docker services stopped"
}

# =============================================================================
# Playwright Setup
# =============================================================================

setup_playwright() {
    log_info "Setting up Playwright..."

    cd "${PROJECT_ROOT}/tests/e2e"

    # Install dependencies
    if [ -f package.json ]; then
        corepack enable
        pnpm install --frozen-lockfile
        pnpm exec playwright install --with-deps
    fi

    # Create auth directory
    mkdir -p .auth

    log_success "Playwright setup complete"
}

# =============================================================================
# Cleanup
# =============================================================================

cleanup() {
    log_warning "Cleaning up E2E test environment..."

    # Stop Docker services
    stop_docker_services

    # Remove generated files
    rm -f "${PROJECT_ROOT}/.env.test"
    rm -f "${PROJECT_ROOT}/migrations/test_seed.sql"
    rm -rf "${PROJECT_ROOT}/ssl"
    rm -rf "${PROJECT_ROOT}/certs"
    rm -rf "${PROJECT_ROOT}/tests/e2e/.auth"
    rm -rf "${PROJECT_ROOT}/tests/e2e/playwright-report"
    rm -rf "${PROJECT_ROOT}/tests/e2e/test-results"

    log_success "Cleanup complete"
}

# =============================================================================
# Main
# =============================================================================

main() {
    local action="${1:-setup}"

    case "$action" in
        --start)
            check_dependencies
            setup_env_file
            generate_ssl_certs
            generate_mtls_certs
            create_seed_sql
            start_docker_services
            setup_playwright
            log_success "E2E test environment ready!"
            echo ""
            echo "Test Credentials:"
            echo "  Admin: ${TEST_ADMIN_EMAIL} / ${TEST_ADMIN_PASSWORD}"
            echo "  Customer: ${TEST_CUSTOMER_EMAIL} / ${TEST_CUSTOMER_PASSWORD}"
            echo ""
            echo "Run tests with: cd tests/e2e && pnpm test"
            ;;
        --clean)
            cleanup
            ;;
        --seed-only)
            create_seed_sql
            # Seed-only intentionally uses direct psql execution via run_seed_sql
            # instead of docker compose exec, so it can target any reachable
            # Postgres configured by .env.test or fall back to a one-shot psql container.
            run_seed_sql "${PROJECT_ROOT}/migrations/test_seed.sql"
            log_success "Test data seeded"
            ;;
        setup|*)
            check_dependencies
            setup_env_file
            generate_ssl_certs
            generate_mtls_certs
            create_seed_sql
            setup_playwright
            log_success "E2E test environment configured!"
            echo ""
            echo "To start services, run: $0 --start"
            echo "To clean up, run: $0 --clean"
            ;;
    esac
}

main "$@"
