#!/bin/bash
# =============================================================================
# VirtueStack E2E Test Setup Script
# =============================================================================
# This script sets up the complete environment for E2E testing:
# - Generates test secrets
# - Seeds test data into the database
# - Creates test users (admin, customer)
# - Configures the Docker stack for testing
#
# Usage:
#   ./scripts/setup-e2e.sh           # Setup only
#   ./scripts/setup-e2e.sh --start   # Setup and start services
#   ./scripts/setup-e2e.sh --clean   # Clean up everything
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Test configuration
TEST_ADMIN_EMAIL="admin@test.virtuestack.local"
TEST_ADMIN_PASSWORD="AdminTest123!"
TEST_ADMIN_TOTP_SECRET="JBSWY3DPEHPK3PXP"  # Base32 encoded test secret

TEST_CUSTOMER_EMAIL="customer@test.virtuestack.local"
TEST_CUSTOMER_PASSWORD="CustomerTest123!"
TEST_CUSTOMER_TOTP_SECRET="KRSXG5DSN5XW4ZLP"

TEST_CUSTOMER_2FA_EMAIL="2fa-customer@test.virtuestack.local"
TEST_CUSTOMER_2FA_PASSWORD="Customer2FA123!"

# =============================================================================
# Helper Functions
# =============================================================================

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

generate_random_string() {
    local length=${1:-32}
    openssl rand -base64 "$length" | tr -d '\n' | head -c "$length"
}

check_dependencies() {
    log_info "Checking dependencies..."

    local missing=()

    # Check for required tools
    for cmd in docker openssl curl jq; do
        if ! command -v "$cmd" &> /dev/null; then
            missing+=("$cmd")
        fi
    done

    if [ ${#missing[@]} -ne 0 ]; then
        log_error "Missing required tools: ${missing[*]}"
        exit 1
    fi

    log_success "All dependencies available"
}

# =============================================================================
# Environment Setup
# =============================================================================

setup_env_file() {
    log_info "Creating .env.test file..."

    cat > "${PROJECT_ROOT}/.env.test" << EOF
# =============================================================================
# VirtueStack E2E Test Environment
# =============================================================================
# Generated by setup-e2e.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT USE IN PRODUCTION
# =============================================================================

# PostgreSQL
POSTGRES_USER=virtuestack
POSTGRES_PASSWORD=virtuestack_test_password
POSTGRES_DB=virtuestack

# NATS
NATS_AUTH_TOKEN=virtuestack_nats_test_token

# JWT Configuration (32+ character secret)
JWT_SECRET=$(generate_random_string 64)

# Encryption Key (32 bytes, hex encoded)
ENCRYPTION_KEY=0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef

# Logging
LOG_LEVEL=debug
CORS_ORIGINS=http://localhost:3000,http://localhost:3001

# WebUI Configuration
NEXT_PUBLIC_API_URL=http://localhost:8080/api/v1
ADMIN_URL=http://localhost:3000
CUSTOMER_URL=http://localhost:3001
BASE_URL=http://localhost:8080

# Test Credentials
TEST_ADMIN_EMAIL=${TEST_ADMIN_EMAIL}
TEST_ADMIN_PASSWORD=${TEST_ADMIN_PASSWORD}
TEST_ADMIN_TOTP_SECRET=${TEST_ADMIN_TOTP_SECRET}

TEST_CUSTOMER_EMAIL=${TEST_CUSTOMER_EMAIL}
TEST_CUSTOMER_PASSWORD=${TEST_CUSTOMER_PASSWORD}
TEST_CUSTOMER_TOTP_SECRET=${TEST_CUSTOMER_TOTP_SECRET}

# Storage (for Node Agent testing)
STORAGE_BACKEND=ceph
CEPH_POOL=vs-vms
CEPH_USER=virtuestack

# SSL (self-signed for testing)
SSL_CERT_PATH=./ssl/cert.pem
SSL_KEY_PATH=./ssl/key.pem
EOF

    log_success "Created .env.test"
}

# =============================================================================
# SSL Certificate Generation
# =============================================================================

generate_ssl_certs() {
    log_info "Generating SSL certificates for testing..."

    local ssl_dir="${PROJECT_ROOT}/ssl"
    mkdir -p "$ssl_dir"

    # Generate self-signed certificate
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout "${ssl_dir}/key.pem" \
        -out "${ssl_dir}/cert.pem" \
        -subj "/C=US/ST=Test/L=Test/O=VirtueStack/OU=Testing/CN=localhost" \
        -addext "subjectAltName=DNS:localhost,DNS:*.localhost,IP:127.0.0.1" \
        2>/dev/null

    # Set permissions
    chmod 600 "${ssl_dir}/key.pem"
    chmod 644 "${ssl_dir}/cert.pem"

    log_success "Generated SSL certificates"
}

# =============================================================================
# mTLS Certificate Generation
# =============================================================================

generate_mtls_certs() {
    log_info "Generating mTLS certificates for Controller-Node Agent communication..."

    local certs_dir="${PROJECT_ROOT}/certs"
    mkdir -p "$certs_dir"

    # Generate CA
    openssl genrsa -out "${certs_dir}/ca.key" 4096 2>/dev/null
    openssl req -new -x509 -days 365 -key "${certs_dir}/ca.key" \
        -out "${certs_dir}/ca.crt" \
        -subj "/C=US/ST=Test/L=Test/O=VirtueStack/OU=CA/CN=VirtueStack Test CA" \
        2>/dev/null

    # Generate Controller certificate
    openssl genrsa -out "${certs_dir}/controller.key" 4096 2>/dev/null
    openssl req -new -key "${certs_dir}/controller.key" \
        -out "${certs_dir}/controller.csr" \
        -subj "/C=US/ST=Test/L=Test/O=VirtueStack/OU=Controller/CN=controller" \
        2>/dev/null
    openssl x509 -req -days 365 -in "${certs_dir}/controller.csr" \
        -CA "${certs_dir}/ca.crt" -CAkey "${certs_dir}/ca.key" -CAcreateserial \
        -out "${certs_dir}/controller.crt" \
        -extfile <(echo "subjectAltName=DNS:controller,DNS:localhost,IP:127.0.0.1") \
        2>/dev/null
    rm -f "${certs_dir}/controller.csr"

    # Generate Node Agent certificate
    openssl genrsa -out "${certs_dir}/node-agent.key" 4096 2>/dev/null
    openssl req -new -key "${certs_dir}/node-agent.key" \
        -out "${certs_dir}/node-agent.csr" \
        -subj "/C=US/ST=Test/L=Test/O=VirtueStack/OU=Node Agent/CN=node-agent" \
        2>/dev/null
    openssl x509 -req -days 365 -in "${certs_dir}/node-agent.csr" \
        -CA "${certs_dir}/ca.crt" -CAkey "${certs_dir}/ca.key" -CAcreateserial \
        -out "${certs_dir}/node-agent.crt" \
        -extfile <(echo "subjectAltName=DNS:node-agent,DNS:localhost,IP:127.0.0.1") \
        2>/dev/null
    rm -f "${certs_dir}/node-agent.csr"

    # Set permissions
    chmod 600 "${certs_dir}"/*.key
    chmod 644 "${certs_dir}"/*.crt

    log_success "Generated mTLS certificates"
}

# =============================================================================
# Database Seed Data
# =============================================================================

create_seed_sql() {
    log_info "Creating database seed SQL..."

    local seed_file="${PROJECT_ROOT}/migrations/test_seed.sql"

    cat > "$seed_file" << 'EOF'
-- =============================================================================
-- VirtueStack E2E Test Seed Data
-- =============================================================================
-- This file creates test data for E2E testing.
-- Run with: psql -f migrations/test_seed.sql
-- =============================================================================

BEGIN;

-- Clear existing test data (if any)
DELETE FROM customers WHERE email LIKE '%@test.virtuestack.local';
DELETE FROM admins WHERE email LIKE '%@test.virtuestack.local';
DELETE FROM vms WHERE hostname LIKE 'test-vm-%';
DELETE FROM nodes WHERE hostname LIKE 'test-node-%';
DELETE FROM plans WHERE slug LIKE 'test-%';
DELETE FROM templates WHERE name LIKE 'Test %';
DELETE FROM ip_sets WHERE name LIKE 'Test %';

-- =============================================================================
-- Test Plans
-- =============================================================================
INSERT INTO plans (id, name, slug, vcpu, memory_mb, disk_gb, port_speed_mbps, storage_backend, snapshot_limit, backup_limit, iso_upload_limit, created_at, updated_at)
VALUES
    ('11111111-1111-1111-1111-111111111001', 'Test Basic', 'test-basic', 1, 1024, 10, 100, 'ceph', 2, 2, 2, NOW(), NOW()),
    ('11111111-1111-1111-1111-111111111002', 'Test Standard', 'test-standard', 2, 2048, 25, 500, 'ceph', 3, 3, 3, NOW(), NOW()),
    ('11111111-1111-1111-1111-111111111003', 'Test Premium', 'test-premium', 4, 4096, 50, 1000, 'ceph', 5, 5, 5, NOW(), NOW()),
    ('11111111-1111-1111-1111-111111111004', 'Test QCOW Basic', 'test-qcow-basic', 1, 1024, 10, 100, 'qcow', 2, 2, 2, NOW(), NOW());

-- =============================================================================
-- Test Locations
-- =============================================================================
INSERT INTO locations (id, name, region, country, created_at)
VALUES
    ('22222222-2222-2222-2222-222222222001', 'Test US East', 'us-east', 'US', NOW()),
    ('22222222-2222-2222-2222-222222222002', 'Test EU West', 'eu-west', 'DE', NOW());

-- =============================================================================
-- Test Nodes
-- =============================================================================
INSERT INTO nodes (id, hostname, grpc_address, management_ip, status, storage_backend, location_id, created_at, updated_at)
VALUES
    ('33333333-3333-3333-3333-333333333001', 'test-node-1', '10.0.0.101:50051', '10.0.0.101', 'online', 'ceph', '22222222-2222-2222-2222-222222222001', NOW(), NOW()),
    ('33333333-3333-3333-3333-333333333002', 'test-node-2', '10.0.0.102:50051', '10.0.0.102', 'online', 'ceph', '22222222-2222-2222-2222-222222222001', NOW(), NOW()),
    ('33333333-3333-3333-3333-333333333003', 'test-node-qcow', '10.0.0.103:50051', '10.0.0.103', 'online', 'qcow', '22222222-2222-2222-2222-222222222002', NOW(), NOW()),
    ('33333333-3333-3333-3333-333333333004', 'test-node-offline', '10.0.0.104:50051', '10.0.0.104', 'offline', 'ceph', '22222222-2222-2222-2222-222222222001', NOW(), NOW()),
    ('33333333-3333-3333-3333-333333333005', 'test-node-draining', '10.0.0.105:50051', '10.0.0.105', 'draining', 'ceph', '22222222-2222-2222-2222-222222222001', NOW(), NOW());

-- =============================================================================
-- Test IP Sets
-- =============================================================================
INSERT INTO ip_sets (id, name, location_id, network, gateway, created_at)
VALUES
    ('44444444-4444-4444-4444-444444444001', 'Test Public IPv4', '22222222-2222-2222-2222-222222222001', '192.168.100.0/24', '192.168.100.1', NOW()),
    ('44444444-4444-4444-4444-444444444002', 'Test Private IPv4', '22222222-2222-2222-2222-222222222001', '10.10.0.0/24', '10.10.0.1', NOW());

-- Insert test IP addresses
INSERT INTO ip_addresses (id, ip_set_id, address, status, created_at)
SELECT
    '55555555-5555-5555-5555-' || LPAD(i::text, 12, '0'),
    '44444444-4444-4444-4444-444444444001',
    '192.168.100.' || (10 + i)::text,
    CASE WHEN i < 5 THEN 'used' ELSE 'available' END,
    NOW()
FROM generate_series(0, 19) AS i;

-- =============================================================================
-- Test Templates
-- =============================================================================
INSERT INTO templates (id, name, os_family, os_version, rbd_image, rbd_snapshot, storage_backend, created_at, updated_at)
VALUES
    ('66666666-6666-6666-6666-666666666001', 'Test Ubuntu 22.04', 'Linux', '22.04', 'ubuntu-22.04-server', 'v1', 'ceph', NOW(), NOW()),
    ('66666666-6666-6666-6666-666666666002', 'Test Debian 12', 'Linux', '12', 'debian-12-server', 'v1', 'ceph', NOW(), NOW()),
    ('66666666-6666-6666-6666-666666666003', 'Test CentOS 9', 'Linux', '9', 'centos-9-stream', 'v1', 'ceph', NOW(), NOW()),
    ('66666666-6666-6666-6666-666666666004', 'Test Windows Server 2022', 'Windows', '2022', 'windows-server-2022', 'v1', 'ceph', NOW(), NOW()),
    ('66666666-6666-6666-6666-666666666005', 'Test FreeBSD 14', 'BSD', '14', 'freebsd-14', 'v1', 'ceph', NOW(), NOW());

-- =============================================================================
-- Test Admin Users
-- =============================================================================
-- Admin without 2FA (password: AdminTest123!)
INSERT INTO admins (id, email, password_hash, name, role, totp_enabled, totp_secret_encrypted, created_at)
VALUES (
    '77777777-7777-7777-7777-777777777001',
    'admin@test.virtuestack.local',
    '$argon2id$v=19$m=65536,t=3,p=4$S+4lP6LDPZgCKaERGc7yMQ$ZRaIllNMvmxRCle1paxjBWfyMIRkUaXrdgLdW73ThnU',
    'Test Admin',
    'admin',
    FALSE,
    '',
    NOW()
);

-- Admin with 2FA enabled (TOTP secret: JBSWY3DPEHPK3PXP)
INSERT INTO admins (id, email, password_hash, name, role, totp_enabled, totp_secret_encrypted, created_at)
VALUES (
    '77777777-7777-7777-7777-777777777002',
    '2fa-admin@test.virtuestack.local',
    '$argon2id$v=19$m=65536,t=3,p=4$S+4lP6LDPZgCKaERGc7yMQ$ZRaIllNMvmxRCle1paxjBWfyMIRkUaXrdgLdW73ThnU',
    'Test Admin 2FA',
    'admin',
    TRUE,
    'LSj2tuwJzbzTxqimms8+j+LH95O9qzb1fQaxFHSolD5FiEMFlcbFeKONGH0=',
    NOW()
);

-- Super Admin
INSERT INTO admins (id, email, password_hash, name, role, totp_enabled, totp_secret_encrypted, created_at)
VALUES (
    '77777777-7777-7777-7777-777777777003',
    'superadmin@test.virtuestack.local',
    '$argon2id$v=19$m=65536,t=3,p=4$S+4lP6LDPZgCKaERGc7yMQ$ZRaIllNMvmxRCle1paxjBWfyMIRkUaXrdgLdW73ThnU',
    'Super Admin',
    'super_admin',
    FALSE,
    '',
    NOW()
);

-- =============================================================================
-- Test Customer Users
-- =============================================================================
-- Customer without 2FA (password: CustomerTest123!)
INSERT INTO customers (id, email, password_hash, name, status, created_at, updated_at)
VALUES (
    '88888888-8888-8888-8888-888888888001',
    'customer@test.virtuestack.local',
    '$argon2id$v=19$m=65536,t=3,p=4$UckSPc1laEy1U6CPKSY6JQ$oKfM23Fl2O8AHupuNCQwiquIRmdfb2GXzVP0w9P4tIE',
    'Test Customer',
    'active',
    NOW(),
    NOW()
);

-- Customer with 2FA enabled (TOTP secret: KRSXG5DSN5XW4ZLP)
INSERT INTO customers (id, email, password_hash, name, status, totp_secret_encrypted, created_at, updated_at)
VALUES (
    '88888888-8888-8888-8888-888888888002',
    '2fa-customer@test.virtuestack.local',
    '$argon2id$v=19$m=65536,t=3,p=4$lP8KMMeCZBzY9SlR7OOKJw$5J9Mnp5bWaCLkayfl72cUBgf5pc7JHYXDDUBFmuRg6w',
    'Test Customer 2FA',
    'active',
    'C572A12EWu8TUDzhpuFKLnOX6Kg19wJDq6dt11Lxn1jgSFVeUHWilejBFSY=',
    NOW(),
    NOW()
);

-- Suspended customer
INSERT INTO customers (id, email, password_hash, name, status, created_at, updated_at)
VALUES (
    '88888888-8888-8888-8888-888888888003',
    'suspended@test.virtuestack.local',
    '$argon2id$v=19$m=65536,t=3,p=4$UckSPc1laEy1U6CPKSY6JQ$oKfM23Fl2O8AHupuNCQwiquIRmdfb2GXzVP0w9P4tIE',
    'Suspended Customer',
    'suspended',
    NOW(),
    NOW()
);

-- =============================================================================
-- Test VMs for Customer
-- =============================================================================
-- Running VM
INSERT INTO vms (id, customer_id, node_id, plan_id, hostname, status, storage_backend, disk_path, created_at, updated_at)
VALUES (
    '99999999-9999-9999-9999-999999999001',
    '88888888-8888-8888-8888-888888888001',
    '33333333-3333-3333-3333-333333333001',
    '11111111-1111-1111-1111-111111111002',
    'test-vm-running',
    'running',
    'ceph',
    'vs-vms/vs-99999999-9999-9999-9999-999999999001-disk0',
    NOW(),
    NOW()
);

-- Stopped VM
INSERT INTO vms (id, customer_id, node_id, plan_id, hostname, status, storage_backend, disk_path, created_at, updated_at)
VALUES (
    '99999999-9999-9999-9999-999999999002',
    '88888888-8888-8888-8888-888888888001',
    '33333333-3333-3333-3333-333333333001',
    '11111111-1111-1111-1111-111111111001',
    'test-vm-stopped',
    'stopped',
    'ceph',
    'vs-vms/vs-99999999-9999-9999-9999-999999999002-disk0',
    NOW(),
    NOW()
);

-- Provisioning VM
INSERT INTO vms (id, customer_id, node_id, plan_id, hostname, status, storage_backend, created_at, updated_at)
VALUES (
    '99999999-9999-9999-9999-999999999003',
    '88888888-8888-8888-8888-888888888001',
    '33333333-3333-3333-3333-333333333002',
    '11111111-1111-1111-1111-111111111003',
    'test-vm-provisioning',
    'provisioning',
    'ceph',
    NOW(),
    NOW()
);

-- =============================================================================
-- Test Backups
-- =============================================================================
INSERT INTO backups (id, vm_id, type, status, storage_path, size_bytes, created_at)
VALUES
    ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa01', '99999999-9999-9999-9999-999999999001', 'full', 'completed', 'vs-backups/backup-01', 10737418240, NOW() - INTERVAL '1 day'),
    ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa02', '99999999-9999-9999-9999-999999999001', 'full', 'completed', 'vs-backups/backup-02', 1073741824, NOW() - INTERVAL '12 hours'),
    ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaa03', '99999999-9999-9999-9999-999999999001', 'full', 'creating', NULL, NULL, NOW());

-- =============================================================================
-- Test Snapshots
-- =============================================================================
INSERT INTO snapshots (id, vm_id, name, rbd_snapshot, created_at)
VALUES
    ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb01', '99999999-9999-9999-9999-999999999001', 'before-update', 'snap-before-update', NOW() - INTERVAL '2 days'),
    ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb02', '99999999-9999-9999-9999-999999999001', 'daily-backup', 'snap-daily-' || to_char(NOW() - INTERVAL '1 day', 'YYYYMMDD'), NOW() - INTERVAL '1 day'),
    ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbb03', '99999999-9999-9999-9999-999999999002', 'initial', 'snap-initial', NOW() - INTERVAL '3 days');

-- =============================================================================
-- Test API Keys for Customer
-- =============================================================================
INSERT INTO customer_api_keys (id, customer_id, name, key_hash, permissions, expires_at, created_at)
VALUES
    ('cccccccc-cccc-cccc-cccc-cccccccccc01', '88888888-8888-8888-8888-888888888001', 'Test API Key', '$argon2id$v=19$m=65536,t=3,p=4$YXBpa2V5c2FsdA$apikeyhashfortesting1234567890abcdef', '["vm:read","vm:start","vm:stop"]', NOW() + INTERVAL '30 days', NOW()),
    ('cccccccc-cccc-cccc-cccc-cccccccccc02', '88888888-8888-8888-8888-888888888001', 'Expired Key', '$argon2id$v=19$m=65536,t=3,p=4$ZXhwaXJlZGtleQ$expiredkeyhash1234567890abcdef', '["vm:read"]', NOW() - INTERVAL '1 day', NOW() - INTERVAL '31 days');

-- =============================================================================
-- Assign IP addresses to test VMs
-- =============================================================================
UPDATE ip_addresses SET vm_id = '99999999-9999-9999-9999-999999999001', customer_id = '88888888-8888-8888-8888-888888888001', status = 'used'
WHERE address IN ('192.168.100.10', '192.168.100.11');

UPDATE ip_addresses SET vm_id = '99999999-9999-9999-9999-999999999002', customer_id = '88888888-8888-8888-8888-888888888001', status = 'used'
WHERE address = '192.168.100.12';

-- =============================================================================
-- Test Webhooks
-- =============================================================================
INSERT INTO customer_webhooks (id, customer_id, name, url, secret, events, created_at)
VALUES
    ('dddddddd-dddd-dddd-dddd-dddddddddd01', '88888888-8888-8888-8888-888888888001', 'Test Webhook', 'https://webhook.example.com/test', 'test-webhook-secret', '["vm.created","vm.deleted","vm.status_changed"]', NOW());

COMMIT;

-- =============================================================================
-- Summary
-- =============================================================================
SELECT 'E2E Test Seed Data Loaded' AS status;
SELECT
    'Test Plans: ' || (SELECT COUNT(*) FROM plans WHERE slug LIKE 'test-%') ||
    ', Test Nodes: ' || (SELECT COUNT(*) FROM nodes WHERE hostname LIKE 'test-node-%') ||
    ', Test VMs: ' || (SELECT COUNT(*) FROM vms WHERE hostname LIKE 'test-vm-%') ||
    ', Test Customers: ' || (SELECT COUNT(*) FROM customers WHERE email LIKE '%@test.virtuestack.local') ||
    ', Test Admins: ' || (SELECT COUNT(*) FROM admins WHERE email LIKE '%@test.virtuestack.local')
    AS summary;
EOF

    log_success "Created seed SQL: $seed_file"
}

# =============================================================================
# Docker Services
# =============================================================================

start_docker_services() {
    log_info "Starting Docker services..."

    cd "$PROJECT_ROOT"

    # Copy test env to .env for docker-compose
    if [ -f .env.test ]; then
        cp .env.test .env
    fi

    # Build images
    docker compose build

    # Start services
    docker compose up -d

    # Wait for services to be healthy
    log_info "Waiting for services to be healthy..."
    sleep 10

    # Check PostgreSQL
    for i in {1..30}; do
        if docker compose exec -T postgres pg_isready -U virtuestack -d virtuestack 2>/dev/null; then
            log_success "PostgreSQL is ready"
            break
        fi
        sleep 1
    done

    # Check NATS
    for i in {1..30}; do
        if docker compose exec -T nats wget --spider -q http://localhost:8222/healthz 2>/dev/null; then
            log_success "NATS is ready"
            break
        fi
        sleep 1
    done

    # Check Controller
    for i in {1..30}; do
        if curl -sf http://localhost:8080/health > /dev/null 2>&1; then
            log_success "Controller is ready"
            break
        fi
        sleep 1
    done

    # Run migrations
    log_info "Running database migrations..."
    docker compose exec -T controller migrate -path /migrations -database "postgresql://virtuestack:virtuestack_test_password@postgres:5432/virtuestack?sslmode=disable" up

    # Seed test data
    log_info "Seeding test data..."
    docker compose exec -T postgres psql -U virtuestack -d virtuestack -f /docker-entrypoint-initdb.d/../migrations/test_seed.sql 2>/dev/null || \
        docker compose exec -T postgres psql -U virtuestack -d virtuestack < "${PROJECT_ROOT}/migrations/test_seed.sql"

    log_success "All services started and healthy"
}

stop_docker_services() {
    log_info "Stopping Docker services..."

    cd "$PROJECT_ROOT"
    docker compose down -v

    log_success "Docker services stopped"
}

# =============================================================================
# Playwright Setup
# =============================================================================

setup_playwright() {
    log_info "Setting up Playwright..."

    cd "${PROJECT_ROOT}/tests/e2e"

    # Install dependencies
    if [ -f package.json ]; then
        corepack enable
        pnpm install --frozen-lockfile --ignore-scripts
        pnpm exec playwright install --with-deps
    fi

    # Create auth directory
    mkdir -p .auth

    log_success "Playwright setup complete"
}

# =============================================================================
# Cleanup
# =============================================================================

cleanup() {
    log_warning "Cleaning up E2E test environment..."

    # Stop Docker services
    stop_docker_services

    # Remove generated files
    rm -f "${PROJECT_ROOT}/.env.test"
    rm -f "${PROJECT_ROOT}/migrations/test_seed.sql"
    rm -rf "${PROJECT_ROOT}/ssl"
    rm -rf "${PROJECT_ROOT}/certs"
    rm -rf "${PROJECT_ROOT}/tests/e2e/.auth"
    rm -rf "${PROJECT_ROOT}/tests/e2e/playwright-report"
    rm -rf "${PROJECT_ROOT}/tests/e2e/test-results"

    log_success "Cleanup complete"
}

# =============================================================================
# Main
# =============================================================================

main() {
    local action="${1:-setup}"

    case "$action" in
        --start)
            check_dependencies
            setup_env_file
            generate_ssl_certs
            generate_mtls_certs
            create_seed_sql
            start_docker_services
            setup_playwright
            log_success "E2E test environment ready!"
            echo ""
            echo "Test Credentials:"
            echo "  Admin: ${TEST_ADMIN_EMAIL} / ${TEST_ADMIN_PASSWORD}"
            echo "  Customer: ${TEST_CUSTOMER_EMAIL} / ${TEST_CUSTOMER_PASSWORD}"
            echo ""
            echo "Run tests with: cd tests/e2e && pnpm test"
            ;;
        --clean)
            cleanup
            ;;
        --seed-only)
            create_seed_sql
            docker compose exec -T postgres psql -U virtuestack -d virtuestack < "${PROJECT_ROOT}/migrations/test_seed.sql"
            log_success "Test data seeded"
            ;;
        setup|*)
            check_dependencies
            setup_env_file
            generate_ssl_certs
            generate_mtls_certs
            create_seed_sql
            setup_playwright
            log_success "E2E test environment configured!"
            echo ""
            echo "To start services, run: $0 --start"
            echo "To clean up, run: $0 --clean"
            ;;
    esac
}

main "$@"
